### ISSUE TITLE
ZK Sync test wallet ____not showing Zero Knowledge Proof

### ISSUE THREAD

**Issue by junaid02012** [matter-labs/zksync#224]
Hi,

I went through the live demo of Zksync wallet and performed some transactions. But as ZK sync claims that it implements Zero Knowledge Proof, therefore, I was assuming that the transactions should be private and will not show the details for the sender, receiver, and the amount being transacted. But the result was against the expectations and all the details were included in the transaction details.

Can anyone tell me how can I look into the exact behaviour of Zero-Knowledge Proof in ZK sync?
![ZK sync transaction](https://user-images.githubusercontent.com/61004937/76057481-7e320b80-5f9b-11ea-99fe-7f75b6c14e0d.jpg)

**Comment by skywinder** [comment]
ZKSync is a scaling solution first. There is not privacy functionality (yet). 

As readme says:

> the public data update for every block is published over the mainchain network in the cheap calldata.

P.s. for future reference, I would recommend listen zk podcast with Alex intro, how zksync works under the hood. 
https://youtu.be/JXWjn9sGL6c
