### ISSUE TITLE
some issues when testing zksync in AlphaWallet browser

### ISSUE THREAD

**Issue by zhangzhongnan928** [matter-labs/zksync#227]
I can successfully deposit ETH, but it shows error as below
![image](https://user-images.githubusercontent.com/33795543/84728623-f1a0db80-afd4-11ea-89d9-d50c390a8489.png)

I cannot transfer or withdraw, it shows error as below 
![image](https://user-images.githubusercontent.com/33795543/84728693-27de5b00-afd5-11ea-89b6-1d294a600774.gif)

![image](https://user-images.githubusercontent.com/33795543/84728781-68d66f80-afd5-11ea-8bb5-4a970c8a02e1.png)

**Comment by gluk64** [comment]
Thank you for reporting! What wallet are you using?

**Comment by zhangzhongnan928** [comment]
> Thank you for reporting! What wallet are you using?

Hi, I'm using AlphaWallet iOS, https://github.com/AlphaWallet/alpha-wallet-ios

**Comment by gluk64** [comment]
Oh, sorry, it's right in the title 🙈

Will check.

**Comment by gluk64** [comment]
We could reproduce it in AlphaWallet, the team is taking care of the fix.

**Comment by nosovk** [comment]
@zhangzhongnan928 could you please help to enable debug in alphawallet.
https://github.com/AlphaWallet/alpha-wallet-android/issues/404
currently debug for webview disabled in AlphaWallet, it means that we need special build to debug it if we want to solve an issue.

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 could you please help to enable debug in alphawallet.
> [AlphaWallet/alpha-wallet-android#404](https://github.com/AlphaWallet/alpha-wallet-android/issues/404)
> currently debug for webview disabled in AlphaWallet, it means that we need special build to debug it if we want to solve an issue.

I will ping @JamesSmartCell

**Comment by zhangzhongnan928** [comment]
BTW, I'm using AlphaWallet iOS, I haven't tested on Andriod.

**Comment by nosovk** [comment]
the same bug present on Android, but running debug on Android much  easier.

**Comment by nosovk** [comment]
is there any release plan?
Latest update in market was 7 days ago, just before accepted fix. Is there some release map?

**Comment by zhangzhongnan928** [comment]
![image](https://user-images.githubusercontent.com/33795543/85563888-236b0f80-b671-11ea-9f20-e94f14a11b30.png)

Recently, when testing on iOS

**Comment by nosovk** [comment]
It seems to be another problem, solution is to add BigInt polyfill, I will leave additional comment after landing fix to production.

**Comment by nosovk** [comment]
@zhangzhongnan928 seems to be fixed for now, haven't issue for now. Please close if it's not reproduced any more at yours device.
