### ISSUE TITLE
Metamask wallet

### ISSUE THREAD

**Issue by paulyeki** [matter-labs/zksync#228]
I can't get it to open and sign for a key I had already managed to send some eth to the wallet address from metamask so know when try to find the account  it gives me a error not enough I have even tried and have send out the tweet to get some from to use I had read your medium post to as you say try it out but it's seems really difficult to set up have you not got a way to connect to this wallet on your website cause I have tried it twice know with out success I know your still beta could you take a look thank you

**Comment by paulyeki** [comment]
Error insufficient funds (version=4.0.47)

**Comment by gluk64** [comment]
Hey @paulyeki, can you please send us your account address? You can share it in private to ag@matterlabs.dev
