### ISSUE TITLE
Creating an invoice and verifying payment

### ISSUE THREAD

**Issue by dmidnight** [matter-labs/zksync#232]
As a potential recipient of a zksync payment, I would like to provide an invoice and monitor it for payment. I would also like to prevent underpayment/overpayment.

What is the process for doing this with zksync? The documentation seems rather focused on constructing an outgoing payment, but provides no clarity on what the process looks like for a recipient.

**Comment by dvush** [comment]
That would be great. We are going to support "events" that will track all updates of the account including reasons (account A transferred to account B)

**Comment by adrianchifor** [comment]
This should now be possible with https://checkout.zksync.io/link/ in combination with the [Checkout SDK](https://docs.zksync.io/api/sdk/checkout/)
