### ISSUE TITLE
eip 1271 signatures

### ISSUE THREAD

**Issue by simon-jentzsch** [matter-labs/zksync#236]
Even though zksync support EIP-1271 signatures, those signatures are not deterministic.

Example:
I have a 2 out of 3 Multisig and create a signerkey derrived from my contract-signature, which contains signatures of the first 2 keys. I may loose the second key and generate a valid contract-signature from key1 and key 3. Both signatures are valid, but not the same, which means in both cases different signer-keys would be generated.

**Comment by dvush** [comment]
Thanks, you are correct. We should document this case.
If this happens signer key can be changed to the new one or user can use signer key that is generated using different procedure if this is a problem.
