### ISSUE TITLE
Server RPC-Documentation

### ISSUE THREAD

**Issue by simon-jentzsch** [matter-labs/zksync#237]
I'm currently implementing a client for the server. All I have is the zksync.js-client implementation (which does not contain a lot of comments and a lot of `any` definitions.)
Maybe I missed it, but I am looking for a detailed documentation for those rpc-endpoints :

https://github.com/matter-labs/zksync/blob/master/core/server/src/api_server/rpc_server.rs#L276

**Comment by dvush** [comment]
We don't have detailed doc for this methods, but maybe `js/zksync.js/src/tranport.ts` can help. We use JSONRPC for our protocol.

For example, this code means - call "account_info" method using jsonrpc protocol and use address as a parameter. (this is a client code for the method that you linked)
```typescript
    async getState(address: Address): Promise<AccountState> {
        return await this.transport.request("account_info", [address]);
    }
```


NOTE: we are going to eventually move to more convenient REST api from JSONRPC.

**Comment by simon-jentzsch** [comment]
Thanks, Yes I looked at `transport.ts`, but of course here you see how those endpoints are used, so I'm currently digging through the server code to better understand the expected behavior, because when I sent a transfer to the server (`tx_submit`), I only got an errror-message that some parameter was formated wrong, So currently I'm trying to understand how those are supposed to be formated.

**Comment by popzxc** [comment]
API is now documented and available at https://zksync.io/api/
