### ISSUE TITLE
[zksync npm lib] Error: magic header not detected

### ISSUE THREAD

**Issue by miguelmota** [matter-labs/zksync#238]
Error trying to import [zksync](https://www.npmjs.com/package/zksync) package into application. Any help is appreciated. Thanks in advance

```bash
./node_modules/zksync-crypto/dist/zksync-crypto-bundler_bg.wasm
Module parse failed: magic header not detected
File was processed with these loaders:
 * ./node_modules/file-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
Error: magic header not detected
```

Steps to reproduce:

```bash
npx create-react-app app
npm i zksync
```

```bash
// App.js
async function test() {
  const zksync = await import('zksync')
  console.log(zksync)
}

test()

```

```
$ npm run start
./node_modules/zksync-crypto/dist/zksync-crypto-bundler_bg.wasm
Module parse failed: magic header not detected
File was processed with these loaders:
 * ./node_modules/file-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
Error: magic header not detected
```

```
$ node -v
v11.15.0
```

**Comment by dvush** [comment]
Hi, it looks like your bundler does not support WASM out of the box. 

`You may need an additional loader to handle the result of these loaders.`

Try to use WASM loader in your setup.

**Comment by gluk64** [comment]
hey @miguelmota! Thank you for reporting. We can reproduce it, but, as @dvush pointed out, the problem is that the build system must be wasm-friendly. This is why we recommend using webpack.

Here is more specific information on how to fix it if you want to stick to `react-scripts`:
https://stackoverflow.com/questions/61478832/wasm-react-module-parse-failed-magic-header-not-detected

**Comment by miguelmota** [comment]
Thanks @dvush @gluk64 for pointing me in the right direction.

This is what was needed to get it working:

```bash
npm install --save-dev react-app-rewired wasm-loader 
```

add `config-overrides.js ` with sets wasm loader:

```js
const path = require('path')

module.exports = function override (config, env) {
  const wasmExtensionRegExp = /\.wasm$/
  config.resolve.extensions.push('.wasm')
  config.module.rules.forEach(rule => {
    (rule.oneOf || []).forEach(oneOf => {
      if (oneOf.loader && oneOf.loader.indexOf('file-loader') >= 0) {
        oneOf.exclude.push(wasmExtensionRegExp)
      }
    })
  })

  config.module.rules.push({
    test: wasmExtensionRegExp,
    include: path.resolve(__dirname, 'src'),
    use: [{ loader: require.resolve('wasm-loader'), options: {} }]
  })

  return config
}
```

then in `package.json`, change `react-scripts start` to `react-app-rewired start`:

```json
    "start": "react-app-rewired start",
```
