### ISSUE TITLE
TypeError: tx.wait is undefined

### ISSUE THREAD

**Issue by miguelmota** [matter-labs/zksync#242]
Not sure if this error is on zksync's end or ethers' end but the error `TypeError: tx.wait is undefined` occurs after invoking `syncWallet.onchainAuthSigningKey()`

![Screenshot from 2020-09-02 17-01-39](https://user-images.githubusercontent.com/168240/92049085-3f102780-ed3e-11ea-80c9-9e40398a8888.png)

the transaction goes through and everything however because of this thrown error I'm not able to get back the response object to retrieve tx info

**Comment by dvush** [comment]
Let me check.

**Comment by miguelmota** [comment]
Closing. It was an issue with the ethers Signer.
