### ISSUE TITLE
EIP1271Signature support zk wallet

### ISSUE THREAD

**Issue by junaidev** [matter-labs/zksync#245]
With https://zksync.io/dev/accounts.html#creating-wallet-from-eth-signer signer type can be specified but zksync js lib function for setting signing key via 'EIP 1271 signature' , function is missing?

**Comment by junaidev** [comment]
For Zk Sync keys creation (wallet creation, or first time account registration) by using EIP 1271 signature , is it supported at server side? As there are methods for eip 1271 sig validation https://github.com/matter-labs/zksync/blob/baa5333c8fde5c79aa6bfd00ebbb962fdcfb99f7/core/bin/server/src/eth_watch/mod.rs#L327

**Comment by dvush** [comment]
Signing key can't be set via EIP1271 since we can't guaranty that it stays this way after we verify it on our server. Instead this wallets should use onchain variant of set signing key.
