### ISSUE TITLE
can someone explain how to work with geth?

### ISSUE THREAD

**Issue by jackzhp** [matter-labs/zksync#246]
I don't have any wallet installed, I have only geth installed.
can I use zksync?

thanks.

**Comment by BlockHeader** [comment]
geth is packed in zksync repo. You have to install Metamask (or similar wallet). Otherwise, the demo UI can NOT work.

**Comment by dvush** [comment]
Geth can be used as a wallet, if your look for geth personal API there is a way to do it using JSON RPC api. But I would recommend using metamask or other normal wallets.
