### ISSUE TITLE
Why failed transactions are included in one block?

### ISSUE THREAD

**Issue by StarLI-Trapdoor** [matter-labs/zksync#247]
In seal_pending_block function, the failed txs are included in one block. Those failed txs are NOT verified again when commiting and verified. Suppose one block with failed txs  can NOT generated proof.

      block_transactions.extend(
            pending_block
                .failed_txs
                .into_iter()
                .map(|tx| ExecutedOperations::Tx(Box::new(tx))),
        );
From the git log, the logic is commented and reverted. What's the purpose? Thanks a lot.

**Comment by dvush** [comment]
The idea here is to be able to track when transaction failed - when it was invalid depends on the place in the block where tx was executed. This is purely server detail and to avoid confusion now we display this transactions as reverted in the block explorer.
