### ISSUE TITLE
Trying to deposit with Wallet Connect causes error

### ISSUE THREAD

**Issue by adityapk00** [matter-labs/zksync#249]
I'm using the Chrome web app, and connected it to Trust Wallet on my iPhone connected via WalletConnect. 

Note that the connection succeeds (i.e., the message is signed via Wallet Connect on my Trust Wallet). 

Here's a screenshot of the error.

![image](https://user-images.githubusercontent.com/31996805/94888269-63d6e800-042d-11eb-8f7c-953234c5dd35.png)

**Comment by gluk64** [comment]
Hey @adityapk00, it looks like a problem specific to Trust wallet, but we cannot test it since Trust discontinued the browser support due to a request from Apple :/ (Yes, we need an open alternative to Apple and Google).

Please try a WalletConnect instead.

**Comment by gluk64** [comment]
Oh, you used WalletConnect! My apologies. Will check.

**Comment by gluk64** [comment]
Just tested it with Trust, everything works.

What do you mean by saying "Chrome web app" — https://wallet.zksync.io ?

**Comment by adityapk00** [comment]
Sorry, I should have been clearer. This is the flow that doesn't work and gives the above error:

- Open wallet.zksync.io in Firefox (Same problem with Chrome). No metamask or any other plugin in the browser
- Click on "Wallet Connect" to connect the wallet
- On iPhone, open Trust Wallet, and go to Wallet Connect
- Scan the QR Code on the phone
- Get prompt to sign message in Trust Wallet / Wallet connect on the phone. The connection succeeds
- On the web, click on "Deposit", and select 0.01 ETH
- Click deposit on web

It errors out at this point with the above error. 

If I use metamask on the web browser (Instead of connecting via Trust Wallet / WalletConnect) , everything works as intended.
