### ISSUE TITLE
Test Token Doesn't Work

### ISSUE THREAD

**Issue by araskachoi** [matter-labs/zksync#251]
zkSync connected to metamask gives a warning to use the "Rinkeby Testnet". When changing to the testnet, there is an error that says that zkSync only works with mainnet. This is confusing and makes for a bad UX.

Steps to reproduce:
1. go to https://wallet.zksync.io/
2. specify to connect with metamask
3. login to metamask prompt
4. change network to "Rinkeby"

<img width="1440" alt="Screen Shot 2020-10-27 at 3 43 45 PM" src="https://user-images.githubusercontent.com/13338103/97370266-d93aaa80-186b-11eb-9dbc-ecc072e4855c.png">
<img width="1440" alt="Screen Shot 2020-10-27 at 3 44 28 PM" src="https://user-images.githubusercontent.com/13338103/97370273-da6bd780-186b-11eb-80f1-aa267e31126f.png">
<img width="1440" alt="Screen Shot 2020-10-27 at 3 44 16 PM" src="https://user-images.githubusercontent.com/13338103/97370279-db9d0480-186b-11eb-9bba-98082a29f5a0.png">

**Comment by gluk64** [comment]
Hey @araskachoi, for testing on Rinkeby you need to follow the link in the popup, it will take you to https://rinkeby.zksync.io
