### ISSUE TITLE
Authorizing new public key just works on Ropsten and not on the mainnet !!

### ISSUE THREAD

**Issue by RasoulKhajavi** [matter-labs/zksync#252]
Here is my code : 
*****************************************************************
    const walletPrivateKey = new ethers.Wallet(PrivateKey) ;
    const ethWallet = await walletPrivateKey.connect(ethersProvider);
    const syncWallet = await zksync.Wallet.fromEthSigner(ethWallet, syncProvider);
    
    if (! await syncWallet.isSigningKeySet()) {
        const onchainAuthTransaction = await syncWallet.onchainAuthSigningKey();
        // Wait till transaction is committed on ethereum.
        await onchainAuthTransaction.wait();

        const changePubkey= await syncWallet.setSigningKey({
            feeToken: "ETH",
            fee: ethers.utils.parseEther("0.001")
        });
        // Wait till transaction is committed 
        const receipt = await changePubkey.awaitReceipt();
    }
********************************************************************
Error for the same code on mainnet network : 

Error: insufficient funds for intrinsic transaction cost (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":46,\"error\":{\"code\":-32000,\"message\":\"insufficient funds for gas * price + value\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_sendRawTransaction\",\"params\": ......
***********************************************************************
syncWallet.onchainAuthSigningKey(); 
this function perfectly works on ropsten but not on mainnet! 
is this issue arising from my code or library somehow has an issue ?
thanks for your help in advance.

**Comment by popzxc** [comment]
Well, the error tells that your Ethereum account doesn't have enough funds to authorize ChangePubKey operation onchain.

`onchainAuthSigningKey` method sends a L1 transaction which authorizes ChangePubKey operation in the zkSync smart contract.
Does the account for which you're trying to execute this code have enough funds?

**Comment by Rasoul-Khajavi** [comment]
Thanks @popxzc for your answer
Do you mean my ETH mainnet wallet should have funds?
Well my sync wallet has enough funds both ETH and HEX token , shouldn't it be able to Authorize new pubkey with the funds of the sync wallet? How can I achieve that?

**Comment by RasoulKhajavi** [comment]
Thanks @popzxc for your answer
Do you mean my ETH mainnet wallet should have funds?
Well my sync wallet has enough funds both ETH and HEX token , shouldn't it be able to Authorize new pubkey with the funds of the sync wallet? How can I achieve that?

**Comment by popzxc** [comment]
You invoke `syncWallet.onchainAuthSigningKey()` in your code.
This method is used to authorize `ChangePubKey` operation in the L1 (Ethereum). So, this method sends an Ethereum transaction, and for it to be executed, you should have funds on your Ethereum wallet.

If you want to perform `ChangePubKey` operation in L2 (zkSync) and you have access to your private key (which it seems you have, since in your example you create `ethers.Wallet` from private key), then you don't need to call `syncWallet.onchainAuthSigningKey()` at all: with a private key, this operation will use funds from your L2 account.

**Comment by RasoulKhajavi** [comment]
well if i don't call `syncWallet.onchainAuthSigningKey()` in my code i get this error

**Comment by popzxc** [comment]
1. Do you create a wallet from a private key, or are you using some kind of a smart wallet which manages your private key?
2. Do you call `setSigningKey` the same way as you specified in sample above?

```
    const changePubkey= await syncWallet.setSigningKey({
        feeToken: "ETH",
        fee: ethers.utils.parseEther("0.001")
    });
```

This error ("Change pubkey tx is not authorized onchain") makes me think that you provided an `onchainAuth: true` argument to this call.

**Comment by RasoulKhajavi** [comment]
yes i do ,here is the whole code : 
`const walletPrivateKey = new ethers.Wallet(PrivateKey) ;

    const ethWallet = await walletPrivateKey.connect(ethersProvider);

    const syncWallet = await zksync.Wallet.fromEthSigner(ethWallet, syncProvider);

    if (! await syncWallet.isSigningKeySet()) {

    const changePubkey= await syncWallet.setSigningKey({
        feeToken: "ETH",
        fee: ethers.utils.parseEther("0.001")
    });

    // Wait till transaction is committed
    const receipt = await changePubkey.awaitReceipt();
    
}
`

**Comment by popzxc** [comment]
That looks pretty odd. This kind of error is returned if `ChangePubKey` transaction was sent without an Ethereum signature.
As you can see in the source code, Ethereum signature isn't added **only** if `onchainAuth` argument was passed and its value is `true`: [relevant code in `setSigningKey`](https://github.com/matter-labs/zksync/blob/master/sdk/zksync.js/src/wallet.ts#L380), [relevant code in signing method](https://github.com/matter-labs/zksync/blob/master/sdk/zksync.js/src/wallet.ts#L351).

Thus, if `onchainAuth` argument wasn't passed, sent transaction should not result in the error you provided above.

Is this code snippet is a complete piece of code you're running (apart of `PrivateKey` setting part, of course), or is there something else being executed?

**Comment by RasoulKhajavi** [comment]
yeah it is odd ... that's what i'm trying to figure out . 

the purpose of this code is to just Authorize the account and literally this is all of the code ( except for those lines of importing libraries and initializing providers)
