### ISSUE TITLE
Token Swap on zksync

### ISSUE THREAD

**Issue by gokulsan** [matter-labs/zksync#253]
As zksync supports ERC20 token transfers, is it possible to do a token swap smart contract execution at the moment.

**Comment by gluk64** [comment]
Yes, with the help of multisig. We will publish a library soon that makes this process easy.

**Comment by gokulsan** [comment]
Hi Alex @gluk64 , thank you so much for the pointers. I will explore the possibility of using multisig for token swap using current SDK. Looking forward to see the library coming soon.
