### ISSUE TITLE
zk init  Child process exited with code 1

### ISSUE THREAD

**Issue by xyh393** [matter-labs/zksync#260]
zk init
Creating network "zksync_default" with the default driver
Creating zksync_geth_1       ... done
Creating zksync_postgres_1   ... done
Creating zksync_dev-ticker_1 ... done
Creating zksync_tesseracts_1 ... done
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.58s.
yarn run v1.22.5
$ yarn workspace zksync prepublish
$ yarn build && rollup -c
$ tsc

build/index.js → dist/main.js...
created dist/main.js in 5s
Done in 14.04s.
Usage: axel [options] url1 [url2] [url...]

--max-speed=x		-s x	Specify maximum speed (bytes per second)
--num-connections=x	-n x	Specify maximum number of connections
--output=f		-o f	Specify local output file
--search[=x]		-S [x]	Search for mirrors and download from x servers
--header=x		-H x	Add header string
--user-agent=x		-U x	Set user agent
--no-proxy		-N	Just don't use any proxy server
--quiet			-q	Leave stdout alone
--verbose		-v	More status information
--alternate		-a	Alternate progress indicator
--help			-h	This information
--version		-V	Version information

Visit http://axel.alioth.debian.org/ to report bugs
Error: Child process exited with code 1

I have no idear,I need help ,thanks!

**Comment by dvush** [comment]
seems that your axel tool have some differences in command line arguments. 

here is a version that I have
```
axel --version
Axel version 2.16 (Linux)

Copyright 2001-2007 Wilmer van der Gaast,
	 2007-2009 Giridhar Appaji Nag,
	 2008-2010 Philipp Hagemeister,
	 2015-2017 Joao Eriberto Mota Filho,
	 2016-2017 Stephen Thirlwall,
	 2017      Ismael Luceno,
	 2017      Antonio Quartulli,
		   and others.
Please, see the CREDITS file.
```

**Comment by xyh393** [comment]
Thanks 
My problem has been solved.
