### ISSUE TITLE
hash function choice

### ISSUE THREAD

**Issue by HAOYUatHZ** [matter-labs/zksync#261]
I wonder why Rescue is chosen over other SN(T)ARKs-friendly hash like Poseidon?

Is it because Rescue is more secure (https://eprint.iacr.org/2020/948.pdf page 5 section 4)?

**Comment by shamatar** [comment]
Largely yes. Pedersen is too expensive without custom gates, and with custom gates Rescue is also cheaper. There are fixes for Poseidon that is much faster outside of a circuit and a little more expensive in a circuit. Note and we also use over the roof rounds parameters for rescue, with newer paper suggesting a much lower number to be safe (https://eprint.iacr.org/2020/1143.pdf)

**Comment by HAOYUatHZ** [comment]
> Largely yes. Pedersen is too expensive without custom gates, and with custom gates Rescue is also cheaper. There are fixes for Poseidon that is much faster outside of a circuit and a little more expensive in a circuit. Note and we also use over the roof rounds parameters for rescue, with newer paper suggesting a much lower number to be safe (https://eprint.iacr.org/2020/1143.pdf)

Thanks! @shamatar
