### ISSUE TITLE
Unable to depositToSyncFromEthereum

### ISSUE THREAD

**Issue by elango501** [matter-labs/zksync#262]
I'm trying to transfer eth and getting this error

`async function asyncCall() {
  const syncWallet = zksync.Wallet.fromEthSigner(ethWallet, syncProvider);
  const object = await syncWallet;
  console.log(object.address());

  const deposit = await object.depositToSyncFromEthereum({
    depositTo: object.address(),
    token: 'ETH',
    amount: ethers.utils.parseEther('0.1')
  });
}` 

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'mainContract' of undefined
    at Wallet.<anonymous> (/Users/aequalis/Documents/zksync/node_modules/zksync/build/wallet.js:429:92)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/aequalis/Documents/zksync/node_modules/zksync/build/wallet.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by StanislavBreadless** [comment]
Hi!

Could you please show the code where you initialized `syncProvider`?

It seems like it was initialized incorrect way.

**Comment by elango501** [comment]
> Hi!
> 
> Could you please show the code where you initialized `syncProvider`?
> 
> It seems like it was initialized incorrect way.

var zksync = require('zksync');
var ethers = require ("ethers");
const syncProvider =  zksync.getDefaultProvider('ropsten');
const ethersProvider = new ethers.getDefaultProvider('ropsten');
// Create ethereum wallet using ethers.js
const ethWallet = ethers.Wallet.fromMnemonic(MNEMONIC).connect(ethersProvider);


const syncWallet = zksync.Wallet.fromEthSigner(ethWallet, syncProvider);


async function asyncCall(syncWallet) {
  const object = await syncWallet;
  console.log(object.address());

  const deposit = await object.depositToSyncFromEthereum({
    depositTo: object.address(),
    token: 'ETH',
    amount: ethers.utils.parseEther('0.1')
  });
}



asyncCall(syncWallet);

**Comment by StanislavBreadless** [comment]
> const syncProvider = zksync.getDefaultProvider('ropsten');

`zksync.getDefaultProvider` [returns a promise](https://zksync.io/sdk/js/providers.html#get-default-provider-for-network) and not the provider itself.

**Comment by elango501** [comment]
> > const syncProvider = zksync.getDefaultProvider('ropsten');
> 
> `zksync.getDefaultProvider` [returns a promise](https://zksync.io/sdk/js/providers.html#get-default-provider-for-network) and not the provider itself.

can you some reference example code ?

**Comment by StanislavBreadless** [comment]
In your particular example this should look more like this:

```js
var zksync = require('zksync');
var ethers = require ("ethers");
const ethersProvider = new ethers.getDefaultProvider('ropsten');
// Create ethereum wallet using ethers.js
const ethWallet = ethers.Wallet.fromMnemonic(MNEMONIC).connect(ethersProvider);

async function asyncCall() {
    const syncProvider = await zksync.getDefaultProvider('ropsten');    
    const syncWallet = await zksync.Wallet.fromEthSigner(ethWallet, syncProvider);
    
    console.log(syncWallet.address());

    const deposit = await syncWallet.depositToSyncFromEthereum({
        depositTo: syncWallet.address(),
        token: 'ETH',
        amount: ethers.utils.parseEther('0.1')
    });
}

asyncCall();
```

**Comment by StanislavBreadless** [comment]
@elango501 Did this solve the problem?

**Comment by StanislavBreadless** [comment]
Closing the problem because the solution has been provided
