### ISSUE TITLE
How to test ZK Rollup contracts

### ISSUE THREAD

**Issue by NoCtrlZ** [matter-labs/zksync#263]
# What I'd like to do
I am trying to deploy and test ZK Rollup contracts to the local blockchain network.
First of all, I ran the `npm run test` on the following directory but it didn't work.
https://github.com/matter-labs/zksync/tree/master/contracts

# Problem
There are some missing contracts for example `./TokenInit.sol`.
```
(base) ➜  contracts git:(master) yarn test
yarn run v1.21.1
$ yarn build && zk f mocha -r ts-node/register test/**/*.ts
$ waffle .waffle.json
Error: None of the sub-resolvers resolved "./TokenInit.sol" location.
    at resolverError (/Users/johnson/zksync/node_modules/@resolver-engine/core/build/resolverengine.js:75:32)
    at ResolverEngine.<anonymous> (/Users/johnson/zksync/node_modules/@resolver-engine/core/build/resolverengine.js:52:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/johnson/zksync/node_modules/@resolver-engine/core/build/resolverengine.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

# Question
Can I try ZK Rollup solidity contract on my locally?
Which contracts are working on mainnet?
Are `ZK Rollup` contracts on the way to development?

**Comment by popzxc** [comment]
You have to bootstrap the environment before testing. We have several guides:

- [Setup of the development environment](https://github.com/matter-labs/zksync/blob/master/docs/setup-dev.md)
- [Development hints](https://github.com/matter-labs/zksync/blob/master/docs/development.md)
- [Running the network locally](https://github.com/matter-labs/zksync/blob/master/docs/launch.md)

Answering your question, we have several generated contracts, so prior to testing you have to generate them. This is done automatically within the `zk init` command.

**Comment by NoCtrlZ** [comment]
Thank you!
Very cool!
