### ISSUE TITLE
"TxBatch failed. Reason: zkSync API response error: code 300; message: Error communicating core server"

### ISSUE THREAD

**Issue by GriffGreen** [matter-labs/zksync#266]
Trying to donate to a long list of grants (tried 98 and 96)... feels like the page is just timing out (tho who knows what the problem really is.... oh maybe you! ;-) ) 

Here is the cart: 

https://gitcoin.co/grants/cart/bulk-add/347;1000;316,238;500;316,152;2000;316,539;9000;316,1052;100;316,63;500;316,1700;100;316,1183;100;316,1595;1000;316,1657;100;316,565;100;316,143;1000;316,622;2000;316,1415;500;316,308;3000;316,1634;100;316,437;100;316,1561;200;316,191;500;316,275;1000;316,149;1000;316,500;1000;316,551;100;316,237;300;316,1632;200;316,1101;100;316,1093;300;316,12;100;316,524;1000;316,13;1000;316,855;100;316,160;500;316,1134;200;316,1577;100;316,711;300;316,1240;100;316,1636;100;316,1592;100;316,795;5000;316,517;2000;316,1297;500;316,1141;500;316,1663;500;316,1127;9000;316,277;3000;316,668;1000;316,1609;1000;316,798;1000;316,1155;1000;316,1638;500;316,899;100;316,1118;300;316,1573;400;316,1732;1000;316,1424;300;316,1635;300;316,1643;100;316,1151;500;316,1122;100;316,1158;1500;316,775;500;316,1219;100;316,331;3000;316,1620;100;316,202;2000;316,285;500;316,816;500;316,902;300;316,231;300;316,159;1000;316,779;1000;316,235;300;316,1691;100;316,184;1000;316,590;100;316,207;100;316,515;100;316,1041;200;316,1143;100;316,1175;400;316,1250;500;316,738;200;316,1266;200;316,1403;100;316,514;300;316,1262;1000;316,806;100;316,949;300;316,1210;300;316,1554;400;316,1464;200;316,1618;300;316,848;1000;316,1574;300;316,1641;500;316,1374;500;316,1379;3000;316,1499;400;316,:griffgreen

Here's the slideshow... if you scroll real fast... its like a gif ;-D

![Screen Shot 2020-12-14 at 6 14 54 PM](https://user-images.githubusercontent.com/14945613/102147243-bb9cc100-3e6a-11eb-8f7c-533eb4135dee.png)

![Screen Shot 2020-12-14 at 6 15 10 PM](https://user-images.githubusercontent.com/14945613/102147241-bb042a80-3e6a-11eb-9f50-0e3c2faa952f.png)

![Screen Shot 2020-12-14 at 6 15 26 PM](https://user-images.githubusercontent.com/14945613/102147239-bb042a80-3e6a-11eb-923c-9c4c1de59dd3.png)

![Screen Shot 2020-12-14 at 6 15 43 PM](https://user-images.githubusercontent.com/14945613/102147236-b9d2fd80-3e6a-11eb-9557-15a7ebbf22cc.png)

**Comment by GriffGreen** [comment]
I couldnt get it to work with 71... but it worked with a nice round number of 64 ;-D

I just funded these 64 grants on @gitcoin => https://gitcoin.co/grants/cart/bulk-add/347;1000;316,238;500;316,152;2000;316,539;9000;316,63;500;316,1595;1000;316,143;1000;316,622;2000;316,1415;500;316,308;3000;316,191;500;316,275;1000;316,149;1000;316,500;1000;316,237;300;316,1093;300;316,524;1000;316,13;1000;316,160;500;316,711;300;316,795;5000;316,517;2000;316,1297;500;316,1141;500;316,1663;500;316,1127;9000;316,277;3000;316,668;1000;316,1609;1000;316,798;1000;316,1155;1000;316,1638;500;316,1118;300;316,1573;400;316,1732;1000;316,1424;300;316,1635;300;316,1151;500;316,1158;1500;316,775;500;316,331;3000;316,202;2000;316,285;500;316,816;500;316,902;300;316,231;300;316,159;1000;316,779;1000;316,235;300;316,184;1000;316,590;100;316,1175;400;316,1250;500;316,514;300;316,1262;1000;316,949;300;316,1210;300;316,1554;400;316,1618;300;316,848;1000;316,1574;300;316,1641;500;316,1374;500;316,1379;3000;316,:griffgreen

**Comment by popzxc** [comment]
Indeed, the batch you tried to submit is too big. We will improve the error in that case, and will think about what can we do to improve the overall UX.

Thanks for the report!

**Comment by mds1** [comment]
What is the batch size capped at? Is it some fixed number of transfers, or is it based on the gas required? Wondering how we can account for this on the Gitcoin frontend (see https://github.com/gitcoinco/web/issues/8114)

Also just curious where the limitation comes from? Is this something that will be fixed at the current limit for the forseeable future or can the limit be raised?

**Comment by GriffGreen** [comment]
@mds1 for sure that cart worked... you could limit it at 50 and pray?

what say you @popzxc ?

**Comment by popzxc** [comment]
@mds1 @GriffGreen This is actually based on several independent details: supported block sizes, time to verify all the signatures in the batch, amount of gas required to process the transactions. We're currently preparing the 1.0 API, where the number of transactions in the batch will be limited to 50.

So, for now, you use the same number as a limit on your side.

**Comment by mds1** [comment]
Awesome, so we'll set the limit to 50 transfers. Thanks @popzxc
