### ISSUE TITLE
CORS errors on checkout.zksync.io

### ISSUE THREAD

**Issue by fafrd** [matter-labs/zksync#269]
Hi, I'm trying to check out a gitcoin grants donation via zksync, but I'm getting `Network error`.

It looks like the reason is CORS errors showing up in my terminal:
>Access to XMLHttpRequest at 'https://api.zksync.io/jsrpc' from origin 'https://checkout.zksync.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by dedosmedia** [comment]
Same error here... I am trying to donate a gitcon but it's impossible.

(index):1 Access to XMLHttpRequest at 'https://api.zksync.io/jsrpc' from origin 'https://checkout.zksync.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by dedosmedia** [comment]
That's weird....
I usually work with Charles Web Debugging Proxy... I had it closed, but after opening it to try to inspect the error, it worked flawlessly. Not sure what is causing the issue.

**Comment by popzxc** [comment]
We are aware of the issue and working on the fix. Will try to resolve the issue ASAP.

**Comment by popzxc** [comment]
It should be fixed now.

**Comment by corbt** [comment]
I just had the same issue on checkout.zksync.io. Trying to fund a Gitcoin grant and getting an identical error. I'm on a Mac and using the latest Chrome (Chrome 92.0.4515.131)

> Access to XMLHttpRequest at 'https://api.zksync.io/jsrpc' from origin 'https://checkout.zksync.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by popzxc** [comment]
@StanislavBreadless please look into it.

**Comment by StanislavBreadless** [comment]
> I just had the same issue on checkout.zksync.io. Trying to fund a Gitcoin grant and getting an identical error. I'm on a Mac and using the latest Chrome (Chrome 92.0.4515.131).
> 
> > Access to XMLHttpRequest at 'https://api.zksync.io/jsrpc' from origin 'https://checkout.zksync.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Hi! Thank you for letting us know. Does the issue persist?

**Comment by corbt** [comment]
@StanislavBreadless nope, I just tried again and this time it worked correctly.
