### ISSUE TITLE
zk init issue

### ISSUE THREAD

**Issue by Holt666** [matter-labs/zksync#271]
when i run 'zk init' command, there is some errors:

`Status: Downloaded newer image for matterlabs/dev-ticker:latest
Creating zksync_geth_1       ... error
Creating zksync_postgres_1 ...
Creating zksync_dev-ticker_1 ...

Creating zksync_postgres_1   ... error
es not exist: /Users/holt666/git/zksync/volumes/geth

ERROR: for zksync_postgres_1  Cannot create container for service postgres: invalid mount config for type "bind": bind sourceCreating zksync_dev-ticker_1 ... done

ERROR: for geth  Cannot create container for service geth: invalid mount config for type "bind": bind source path does not exist: /Users/holt666/git/zksync/volumes/geth

ERROR: for postgres  Cannot create container for service postgres: invalid mount config for type "bind": bind source path does not exist: /Users/holt666/git/zksync/volumes/postgres
ERROR: Encountered errors while bringing up the project.
Error: Child process exited with code 1`

after that, i was run 'zk run plonk-setup', there is ok, no erors.

**Comment by popzxc** [comment]
For now, you have to manually create the following folders:

- `/volumes/geth`
- `/volumes/postgres`
- `/volumes/tesseracts`.

We will update `zk` for it to create these folders automatically soon.

**Comment by Holt666** [comment]
ok, this work!thanks!
