### ISSUE TITLE
Not enough ETH to perform a transaction

### ISSUE THREAD

**Issue by ligi** [matter-labs/zksync#275]
This might be the wrong repo - but I found no better one to file this. Please move if there is a better repo for this issue. The issue is best described with these screenshots:

![Selection_364](https://user-images.githubusercontent.com/111600/103481351-baf8aa00-4dda-11eb-92e6-e5c1df05777a.png)

![Selection_366](https://user-images.githubusercontent.com/111600/103481355-c2b84e80-4dda-11eb-898e-269a1a4d0077.png)

**Comment by popzxc** [comment]
@keriat could you check that issue please?

**Comment by adrianchifor** [comment]
This should be resolved
