### ISSUE TITLE
Unable to configure zk sync in local: facing error while starting zk server

### ISSUE THREAD

**Issue by mleoanbarasan** [matter-labs/zksync#276]
Hi, I am trying to configure zk in my local environment to explore the L2 and write the smart contracts using following guids:

https://github.com/matter-labs/zksync/blob/master/docs/setup-dev.md

https://github.com/matter-labs/zksync/blob/master/docs/launch.md

But I am facing following issue while starting zk server:

   Compiling zksync_storage v1.0.0 (/Users/leoanbarasanm/Projects/zksync/zksync/core/lib/storage)
error: error returned from database: database "plasma" does not exist
  --> core/lib/storage/src/chain/account/mod.rs:32:27
   |
32 |           let mut results = sqlx::query_as!(
   |  ___________________________^
33 | |             StorageAccountCreation,
34 | |             "
35 | |                 SELECT * FROM account_creates
...  |
41 | |             true
42 | |         )
   | |_________^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: database "plasma" does not exist
   --> core/lib/storage/src/chain/account/mod.rs:96:36
    |
96  |           let account_balance_diff = sqlx::query_as!(
    |  ____________________________________^
97  | |             StorageAccountUpdate,
98  | |             "
99  | |                 SELECT * FROM account_balance_updates
...   |
103 | |             last_block
104 | |         )
    | |_________^
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: database "plasma" does not exist
   --> core/lib/storage/src/chain/account/mod.rs:108:37
    |
108 |           let account_creation_diff = sqlx::query_as!(
    |  _____________________________________^
109 | |             StorageAccountCreation,
110 | |             "
111 | |                 SELECT * FROM account_creates
...   |
115 | |             last_block
116 | |         )
    | |_________^
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: database "plasma" does not exist
   --> core/lib/storage/src/chain/account/mod.rs:120:35
    |
120 |           let account_pubkey_diff = sqlx::query_as!(
    |  ___________________________________^
121 | |             StorageAccountPubkeyUpdate,
122 | |             "
123 | |                 SELECT * FROM account_pubkey_updates
...   |
127 | |             last_block
128 | |         )
    | |_________^
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: error returned from database: database "plasma" does not exist
   --> core/lib/storage/src/chain/account/mod.rs:198:29
    |
198 |           let maybe_account = sqlx::query_as!(
    |  _____________________________^
199 | |             StorageAccount,
200 | |             "
201 | |                 SELECT * FROM accounts
...   |
204 | |             i64::from(account_id)
205 | |         )
    | |_________^

error[E0698]: type inside `async fn` body must be known in this context
   --> core/lib/storage/src/chain/mempool/mod.rs:222:13
    |
222 |         let batch_id = 0; // Special case: batch_id == 0 <==> transaction is not a part of some batch
    |             ^^^^^^^^ cannot infer type for type `{integer}`
    |
note: the type is part of the `async fn` body because of this `await`
   --> core/lib/storage/src/chain/mempool/mod.rs:229:9
    |
229 | /         sqlx::query!(
230 | |             "INSERT INTO mempool_txs (tx_hash, tx, created_at, eth_sign_data, batch_id)
231 | |             VALUES ($1, $2, $3, $4, $5)",
232 | |             tx_hash,
...   |
238 | |         .execute(self.0.conn())
239 | |         .await?;
    | |______________^

error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
  --> core/lib/storage/src/ethereum/mod.rs:99:53
   |
99 |             let final_hash = eth_op.final_hash.map(|hash| H256::from_slice(&hash));
   |                                                     ^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `Sized` is not implemented for `[u8]`
   = help: unsized locals are gated as an unstable feature
help: function arguments must have a statically known size, borrowed types always have a known size
   |
99 |             let final_hash = eth_op.final_hash.map(|&hash| H256::from_slice(&hash));
   |                                                     ^

warning: unused import: `itertools::Itertools`
 --> core/lib/storage/src/data_restore/mod.rs:4:5
  |
4 | use itertools::Itertools;
  |     ^^^^^^^^^^^^^^^^^^^^

warning: unused import: `sqlx::Done`
 --> core/lib/storage/src/prover/mod.rs:4:5
  |
4 | use sqlx::Done;
  |     ^^^^^^^^^^

error: aborting due to 127 previous errors; 16 warnings emitted

Some errors have detailed explanations: E0277, E0698.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `zksync_storage`

To learn more, run the command again with --verbose.
Error: Child process exited with code 101

**Comment by mleoanbarasan** [comment]
Hi, i have downgraded rust to 1.41.0 to match the given configuration. But now i am facing following error:

error[E0432]: unresolved imports `proc_macro`, `getrandom`
 --> /Users/leoanbarasanm/.cargo/registry/src/github.com-1ecc6299db9ec823/const-random-macro-0.1.11/src/lib.rs:2:5
  |
1 | use getrandom;
  |     ^^^^^^^^^
2 | use proc_macro::*;
  |     ^^^^^^^^^^ use of undeclared type or module `proc_macro`

error[E0433]: failed to resolve: use of undeclared type or module `TokenTree`
  --> /Users/leoanbarasanm/.cargo/registry/src/github.com-1ecc6299db9ec823/const-random-macro-0.1.11/src/lib.rs:17:5
   |
17 |     TokenTree::from(Ident::new(ident, Span::call_site())).into()
   |     ^^^^^^^^^ use of undeclared type or module `TokenTree`

error[E0433]: failed to resolve: use of undeclared type or module `Ident`
  --> /Users/leoanbarasanm/.cargo/registry/src/github.com-1ecc6299db9ec823/const-random-macro-0.1.11/src/lib.rs:17:21
   |
17 |     TokenTree::from(Ident::new(ident, Span::call_site())).into()
   |                     ^^^^^ use of undeclared type or module `Ident`

error[E0433]: failed to resolve: use of undeclared type or module `Span`
  --> /Users/leoanbarasanm/.cargo/registry/src/github.com-1ecc6299db9ec823/const-random-macro-0.1.11/src/lib.rs:17:39
   |
17 |     TokenTree::from(Ident::new(ident, Span::call_site())).into()
   |                                       ^^^^ use of undeclared type or module `Span`

error[E0433]: failed to resolve: use of undeclared type or module `TokenTree`
  --> /Users/leoanbarasanm/.cargo/registry/src/github.com-1ecc6299db9ec823/const-random-macro-0.1.11/src/lib.rs:23:17
   |
23 |         "u8" => TokenTree::from(Literal::u8_suffixed(gen_random())).into(),
   |                 ^^^^^^^^^ use of undeclared type or module `TokenTree`

error[E0433]: failed to resolve: use of undeclared type or module `Literal`
  --> /Users/leoanbarasanm/.cargo/registry/src/github.com-1ecc6299db9ec823/const-random-macro-0.1.11/src/lib.rs:23:33
   |
23 |         "u8" => TokenTree::from(Literal::u8_suffixed(gen_random())).into(),
   |                                 ^^^^^^^ use of undeclared type or module `Literal`

error[E0433]: failed to resolve: use of undeclared type or module `TokenTree`
  --> /Users/leoanbarasanm/.cargo/registry/src/github.com-1ecc6299db9ec823/const-random-macro-0.1.11/src/lib.rs:24:18
   |
24 |         "u16" => TokenTree::from(Literal::u16_suffixed(gen_random())).into(),
   |                  ^^^^^^^^^ use of undeclared type or module `TokenTree`

error[E0433]: failed to resolve: use of undeclared type or module `Literal`
  --> /Users/leoanbarasanm/.cargo/registry/src/github.com-1ecc6299db9ec823/const-random-macro-0.1.11/src/lib.rs:24:34
   |
24 |         "u16" => TokenTree::from(Literal::u16_suffixed(gen_random())).into(),
   |                                  ^^^^^^^ use of undeclared type or module `Literal`

**Comment by popzxc** [comment]
1.41 in the docs is just for example, I guess we should clarify that. It just happened to be the most recent one at the time when the docs were written.

Regarding original issue: we use SQLx for PostgreSQL interaction which checks the queries during the compilation time.
In order to do so, you should have a database with all the migrations applied, and `DATABASE_URL` environment variable must be set to the URL of this database. Password should not be required to connect. In development scenario we use the database spawned via `docker-compose`.

If you have set up a database according to our guides and compilation fails when you just try to compile the project, it means that `DATABASE_URL` variable is missing. To overcome this issue, you should create file named `.env` in the `core/lib/storage` and put `DATABASE_URL={..path to databae}` line there.

Once again, if you set up the database according to our guides, you can re-use `.env.backup` file that is already there, you will only have to run `cp .env.backup .env`.
