### ISSUE TITLE
re-obtain L2 signing key

### ISSUE THREAD

**Issue by HAOYUatHZ** [matter-labs/zksync#278]
zkSync gets L2 key from a signature: https://github.com/matter-labs/zksync/blob/5b936b1855a08033cca7f75d6f87fde106c6e8fd/sdk/zksync.js/src/signer.ts#L235-L255

However, ECDSA is a non-deterministic scheme and signature result may be different every time.

This means an user need to be careful: if she/he loses her/his zksync wallet, she/he will be hard to re-produce the L2 key? 

Though she/he can still force exit from L1.

**Comment by shamatar** [comment]
If user looses his L1 key then exit functionality is "useless" for him as he will not be able to use funds after exit, but as long as user controls his L1 key he can re-derive (derivation is deterministic) or change his L2 key (if for some reason a his secp256k1 implementation produces a different signature)

**Comment by HAOYUatHZ** [comment]
> If user looses his L1 key then exit functionality is "useless" for him as he will not be able to use funds after exit, but as long as user controls his L1 key he can re-derive (derivation is deterministic) or change his L2 key (if for some reason a his secp256k1 implementation produces a different signature)

i see.  i made a mistake.    secp256k1 is deterministic.

**Comment by coinhu** [comment]
i
