### ISSUE TITLE
在zksync项目clone下后执行zk init缺少readfile属性

### ISSUE THREAD

**Issue by simagui** [matter-labs/zksync#280]
在zksync项目clone下后执行zk init后报错缺少readfile属性
error:
ymdeMacBook-Pro:bin ym$ zk init
Error: Cannot read property 'readFile' of undefined

**Comment by popzxc** [comment]
Hi! Did you install all the dependencies, as noted in [setup-dev guide](https://github.com/matter-labs/zksync/blob/master/docs/setup-dev.md)?

**Comment by simagui** [comment]
I found the problem because my environment was not set up well. Thank you for your reply

**Comment by simagui** [comment]
> Hi! Did you install all the dependencies, as noted in [setup-dev guide](https://github.com/matter-labs/zksync/blob/master/docs/setup-dev.md)?

I found the problem because my environment was not set up well. Thank you for your reply
