### ISSUE TITLE
PosegreSQL is started locally, but how does ZK connect to PSQL? I don't have a password for my posegre. I got an error when I started ZK server

### ISSUE THREAD

**Issue by simagui** [matter-labs/zksync#281]
PosegreSQL is started locally, but how does ZK connect to PSQL? I don't have a password for my posegre. I got an error when I started ZK server

error:
error: error returned from database: database "plasma" does not exist
  --> core/lib/storage/src/chain/account/mod.rs:88:36
   |
88 |           let account_balance_diff = sqlx::query_as!(
   |  ____________________________________^
89 | |             StorageAccountUpdate,
90 | |             "
91 | |                 SELECT * FROM account_balance_updates
...  |
95 | |             last_block
96 | |         )
   | |_________^

**Comment by simagui** [comment]
I've created the plasma database

**Comment by simagui** [comment]
Or through which configuration file does zksync link to postgre? Postgre's password is wrong again


error: error returned from database: password authentication failed for user "postgres"
   --> core/lib/storage/src/tokens/mod.rs:194:24
    |
194 |           let db_price = sqlx::query_as!(
    |  ________________________^
195 | |             DbTickerPrice,
196 | |             r#"
197 | |             SELECT * FROM ticker_price
...   |
201 | |             i32::from(token_id)
202 | |         )
    | |_________^
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by popzxc** [comment]
For local development, we start the Postgres via docker-compose. It is done by `zk init` (or `zk up`) command.

Regarding the compilation process, we use SQLx capabilities to type-check queries, thus database should be available with all the migrations (again, it's covered by `zk init` command) by the URL `postgres://postgres@localhost/plasma`. Password should not be required for access.

Finally, if you want to compile the project without `zk` utility (which handles environment variables management), you may do the following:

```
cd $ZKSYNC_HOME/core/lib/storage
cp .env.backup .env
```

This command will create a file with the database URL for SQLx, so the code can compile without any environmental variables being set.

Also, check out the docs we have on the development:

- Installing development dependencies: [docs/setup-dev.md](docs/setup-dev.md).
- Launching zkSync locally: [docs/launch.md](docs/launch.md).
- Development guide: [docs/development.md](docs/development.md).
- Repository architecture overview: [docs/architecture.md](docs/architecture.md).

**Comment by simagui** [comment]
zk init  

build/index.js → dist/main.js...
created dist/main.js in 3.7s
Done in 9.96s.
Usage: axel [options] url1 [url2] [url...]

--max-speed=x		-s x	Specify maximum speed (bytes per second)
--num-connections=x	-n x	Specify maximum number of connections
--output=f		-o f	Specify local output file
--search[=x]		-S [x]	Search for mirrors and download from x servers
--header=x		-H x	Add header string
--user-agent=x		-U x	Set user agent
--no-proxy		-N	Just don't use any proxy server
--quiet			-q	Leave stdout alone
--verbose		-v	More status information
--alternate		-a	Alternate progress indicator
--help			-h	This information
--version		-V	Version information

Report bugs to submit@bugs.debian.org (using reportbug)
Error: Child process exited with code 1

**Comment by popzxc** [comment]
Please check the [guide on setting dependencies up](https://github.com/matter-labs/zksync/blob/master/docs/setup-dev.md) (it was linked above) to install all the dependencies correctly.

**Comment by simagui** [comment]
Thank you for your answer
