### ISSUE TITLE
Axel has been upgraded to version 2.17.10, but SSL is still reporting an error Initializing download: https://universal-setup.ams3.digitaloceanspaces.com/setup_2%5E20.key SSL error: certificate verify failed (null) Error: Child process exited with code 1

### ISSUE THREAD

**Issue by simagui** [matter-labs/zksync#282]
Axel has been upgraded to version 2.17.10, but SSL is still reporting an error
Initializing download: https://universal-setup.ams3.digitaloceanspaces.com/setup_2%5E20.key
SSL error: certificate verify failed
(null)
Error: Child process exited with code 1
![image](https://user-images.githubusercontent.com/46394515/105468540-0d3e3400-5cd2-11eb-85a7-4c042de01229.png)

**Comment by popzxc** [comment]
What happens if you have to open corresponding url ([https://universal-setup.ams3.digitaloceanspaces.com/setup_2%5E20.key](https://universal-setup.ams3.digitaloceanspaces.com/setup_2%5E20.key)) with your browser? Can you download the file from there?

**Comment by simagui** [comment]
Yes, I can download files from this URL

**Comment by simagui** [comment]
> 如果必须使用浏览器打开相应的URL（https://universal-setup.ams3.digitaloceanspaces.com/setup_2%5E20.key），会发生什么情况？您可以从那里下载文件吗？

Yes, I can download files from this URL

**Comment by popzxc** [comment]
And if you run axel manually from the command line, can you download any file from other `https` hosts?

**Comment by simagui** [comment]
> 并且，如果您从命令行手动运行axel，可以从其他`https`主机下载任何文件吗？
No, this will cause an error:
root@ubuntu02:~/wz# axel -n 1 https://universal-setup.ams3.digitaloceanspaces.com/setup_2%5E20.key
Initializing download: https://universal-setup.ams3.digitaloceanspaces.com/setup_2%5E20.key
SSL error: certificate verify failed
(null)

**Comment by simagui** [comment]
> And if you run axel manually from the command line, can you download any file from other `https` hosts?

The same error will be reported when downloading other HTTPS files using Axel. It should be the problem of downloading and installing Axel, I use Ubuntu system, I need to check again why there is such error, please let me know if you have a solution for this part. Thank you for your

**Comment by simagui** [comment]
> 并且，如果您从命令行手动运行axel，可以从其他`https`主机下载任何文件吗？

The highest version of apt-get in Ubuntu is 2.17.5, but 2.17.10 is not available. I used Axel 2.17.10 on the CentOS system for the installation. If that doesn't work is there no other way****

**Comment by simagui** [comment]
> 并且，如果您从命令行手动运行axel，可以从其他`https`主机下载任何文件吗？

The highest version of apt-get in Ubuntu is 2.17.5, but 2.17.10 is not available. I used Axel 2.17.10 on the CentOS system for the installation. If that doesn't work is there no other way？

**Comment by simagui** [comment]
> > 并且，如果您从命令行手动运行axel，可以从其他`https`主机下载任何文件吗？
> > 不，这将导致错误：
> > root @ ubuntu02：〜/ wz＃axel -n 1 [https：//universal-setup.ams3。 digitaloceanspaces.com/setup_2%5E20.key](https://universal-setup.ams3.digitaloceanspaces.com/setup_2%5E20.key)
> > 初始化下载：[https](https://universal-setup.ams3.digitaloceanspaces.com/setup_2%5E20.key) : [//universal-setup.ams3.digitaloceanspaces.com/setup_2%5E20.key](https://universal-setup.ams3.digitaloceanspaces.com/setup_2%5E20.key) 
> > SSL错误：证书验证失败
> > （空）



> 并且，如果您从命令行手动运行axel，可以从其他`https`主机下载任何文件吗？

The highest version of apt-get in Ubuntu is 2.17.5, but 2.17.10 is not available. I used Axel 2.17.10 on the CentOS system for the installation. If that doesn't work is there no other way

**Comment by simagui** [comment]
> 并且，如果您从命令行手动运行axel，可以从其他`https`主机下载任何文件吗？

The maximum version of apt-get axel on Ubuntu is 2.4, and the maximum version of apt-get axel installed with source code is 2.17.5. I use version 2.17.10 of CentOS for installation, if this does not work, there is no other way? Can only build ZKSync using CentOS?

**Comment by popzxc** [comment]
Personally I use 2.17.5 and it works for me, however 2.17.10 is recommended due to some problems observed with earlier versions.
On ubuntu you can build the latest axel version [from source](https://github.com/axel-download-accelerator/axel/releases/tag/v2.17.10) if required.

You may also google for your problem with axel, maybe it's something common and can be fixed easily.
