### ISSUE TITLE
Withdrawal questions:

### ISSUE THREAD

**Issue by djs1215** [matter-labs/zksync#294]
When I withdrew from L2 to L1 wallet, I don't know why the system automatically replaced the uppercase letters in my L1 address with lowercase letters, causing my L1 wallet to not receive the withdrawal

This is the L1 address of my ETH:   
0x9586f4B3dC7C0C3bc2D667CfADCa640896160b91

This is my transaction details from L2 withdrawal to L1:
https://zkscan.io/explorer/transactions/sync-tx:1bee1aaac37208f1606684415a6e5ef6195af1b5735f59f04287af56db4265c0
![image](https://user-images.githubusercontent.com/26431102/110289445-6664eb80-8024-11eb-800a-1f189567419f.png)

Although I only lost a small amount of ETH, I think this is a BUG that cannot be ignored.

**Comment by StanislavBreadless** [comment]
Hi @djs1215 ! 

Sorry for the late reply. The funds have arrived onto your wallet:
https://etherscan.io/address/0x9586f4b3dc7c0c3bc2d667cfadca640896160b91#internaltx

The casing does not matter in Ethereum. The mixed case is used to make sure the address is correct, but lowercase is just fine. If the problem persists it is likely that your wallet does not support receiving funds from smart contracts. You should contact the wallet's support.

**Comment by djs1215** [comment]
> Hi @djs1215 !
> 
> Sorry for the late reply. The funds have arrived onto your wallet:
> https://etherscan.io/address/0x9586f4b3dc7c0c3bc2d667cfadca640896160b91#internaltx
> 
> The casing does not matter in Ethereum. The mixed case is used to make sure the address is correct, but lowercase is just fine. If the problem persists it is likely that your wallet does not support receiving funds from smart contracts. You should contact the wallet's support.

Oh,I see.Thank u so much!
