### ISSUE TITLE
zksync client 

### ISSUE THREAD

**Issue by simagui** [matter-labs/zksync#295]
Why there is no parameter in the package returned by zksync client command. Has the startup client been removed

**Comment by simagui** [comment]
"http://localhost": {
         API_SERVER: "http://localhost:3001",
         ETH_NETWORK: "localhost",
         WS_API_ADDR: "ws://localhost:3031",
         HTTP_RPC_API_ADDR: "http://localhost:3030",
     }
start    client：

zksync client

error: unknown command 'client'. See 'zk --help'.

**Comment by popzxc** [comment]
Not sure what do you mean. Can you elaborate?
