### ISSUE TITLE
Using zkWallet with a local environment

### ISSUE THREAD

**Issue by mmagician** [matter-labs/zksync#296]
As far as I understand, the wallet available to users at https://<network name>.zksync.io/account is (so far) closed-source, so I can't run it locally, right?

Is there any way I could connect your wallet to my local network and be able to test the same functionality?

**Comment by ssing2** [comment]
I have the same question . :)

**Comment by adrianchifor** [comment]
https://github.com/matter-labs/zksync-wallet-vue
