### ISSUE TITLE
miss contract file

### ISSUE THREAD

**Issue by mask-pp** [matter-labs/zksync#298]
I did not find the KeysWithPlonkVerifier.sol contract file [document](https://github.com/matter-labs/zksync/blob/91254821b5de20f51fec782157b2e6a24d79af98/contracts/contracts/Verifier.sol#L6)

**Comment by adrianchifor** [comment]
It's in [.gitignore](https://github.com/matter-labs/zksync/blob/5f47fe9990ec87e3087d32d083d13e6cab331ff1/contracts/.gitignore#L3) as it's auto-generated:
- https://github.com/matter-labs/zksync/blob/1387e44b22f794910867132b361ac12222691268/infrastructure/zk/src/run/verify-keys.ts#L13-L32
