### ISSUE TITLE
typo in docs/protocol.md

### ISSUE THREAD

**Issue by woodstock-xkx** [matter-labs/zksync#300]
In [section 4. withdraw](https://github.com/matter-labs/zksync/blob/master/docs/protocol.md#4-withdraw-partial-exit), the length of withdraw's pubdata should be 45 not 44. Moreover, is it possible to use 5 chunks(rather than 6 chunks) for withdraw? As the withdraw transaction updates only **one** OperationBranch, 5 chunks should suffice.

**Comment by woodstock-xkx** [comment]
@gluk64

**Comment by StanislavBreadless** [comment]
Hi @woodstock-xkx! Thanks for noticing the typo! We'll fix it.

Regarding the chunks amount: yes, it's possible to use 5 chunks. we use 6 chunks for historical reasons mostly; it will be changed in one of the future upgrades.
