### ISSUE TITLE
Misleading comment

### ISSUE THREAD

**Issue by dasaveliev** [matter-labs/zksync#301]
https://github.com/matter-labs/zksync/blob/5f47fe9990ec87e3087d32d083d13e6cab331ff1/contracts/contracts/ZkSync.sol#L618

In fact there is Deposit uninformative event

Please consider returning back
```
event OnchainWithdrawal(
        address indexed owner,
        uint16 indexed tokenId,
        uint128 amount
    );
```

**Comment by StanislavBreadless** [comment]
Hi @dasaveliev ! 

We understand that it would likely be more informative if the event contained the address of the owner, but we decided not to include that field to let the users save gas.

**Comment by StanislavBreadless** [comment]
@dasaveliev 

I am closing this issue. Feel free to re-open it if needed

**Comment by dasaveliev** [comment]
"we decided... "
i will never understand why not ask users what they need and what is more
valuable for them

пн, 29 мар. 2021 г., 14:18 Stanislav Bezkorovainyi ***@***.***
