### ISSUE TITLE
Question： how many circuit gages be generated for one normal transfer transaction ?

### ISSUE THREAD

**Issue by DreamWuGit** [matter-labs/zksync#303]
HI, guys 
I am new to zksync, but interested in some implementation details such as  number of circuit gages be generated for one normal transfer transaction proof ?

similars:  ecdsa signature & hash operation will take how many gates for circuits to handle ?

Thanks a lot!

**Comment by bxpana** [comment]
For zkSync 1.0, it’s 2 chunks per transfer and some X chunks for 2^26 circuit, then it can be computed.
