### ISSUE TITLE
depositToSyncFromEthereum somehow does not work

### ISSUE THREAD

**Issue by jscode017** [matter-labs/zksync#307]
I'm setting up zk sync on the local environment
with:
```
zk up
zk server
zk prover
```

And write a simple script as below
```
import * as zksync from "zksync";
import { Wallet } from "zksync";
import * as ethers from "ethers";

const syncProvider = await zksync.Provider.newHttpProvider("http://localhost:3030");

const ethersProvider = new ethers.providers.JsonRpcProvider("http://localhost:8545");

let privKey="0xcfb3347dfbf70ca6615ceac0f7791cd822ccf96c5cec552367a8380edc4e94f6"
const ethWallet = new ethers.Wallet(privKey,ethersProvider);

const syncWallet = await zksync.Wallet.fromEthSigner(ethWallet, syncProvider);

const deposit = await syncWallet.depositToSyncFromEthereum({
  depositTo: syncWallet.address(),
  token: "ETH",
  amount: ethers.utils.parseEther("1.0"),
});
const depositReceipt = await deposit.awaitReceipt();
const verifiedDepositReceipt = await deposit.awaitVerifyReceipt();
```
all went well, until the 
`const depositReceipt = await deposit.awaitReceipt();
`
this line seems to stuck there forever

And I am pretty sure that on the ethereum network, the transaction from ethereum to the main contract of zk_sync is mined successfully, since I've checked it in the zksync_tesseract1.
Are there something that I've possibiliy do wrong?

**Comment by StanislavBreadless** [comment]
Hi @jscode017 !

Make sure to run `dummy-prover`: https://github.com/matter-labs/zksync/blob/master/docs/development.md#using-dummy-prover

**Comment by jscode017** [comment]
Thanks a lot, that works.
