### ISSUE TITLE
JavaScript SDK: Default Gas Limit For Ropsten Deposit Too low

### ISSUE THREAD

**Issue by owenshen24** [matter-labs/zksync#313]
I am trying to deposit by using `depositToSyncFromEthereum` from the `Wallet` class on `ropsten-beta`. The default gas limit was set to `90,000`, but the actual deposit took `154,000` gas.

I know users can pas in their own custom options using `ethTxOptions`, but it might worth looking into why the estimate given is off.

**Comment by StanislavBreadless** [comment]
Hi @owenshen24 

I have just tested on ropsten both ETH and ERC-20 deposits on the latest beta. Everything works absolutely fine on my side.

Could you please provide some code snippets to reproduce the issue?

**Comment by owenshen24** [comment]
I will need to go and see if I can repro it using the newest SDK.

I realize it's not very helpful, but here is one deposit tx that had previously run out of gas [here](https://ropsten.etherscan.io/tx/0xcd813bb565e96cff9d148958fb46e3f20d3366f7bed8e946a4628f6002e5dd60).

**Comment by StanislavBreadless** [comment]
@owenshen24 

Not sure what's that. Here is the true address for Ropsten: 0xc332679d243439048c8395defde74d71cf5151e7

**Comment by owenshen24** [comment]
Ohhh, I must have done something wrong with my front-end code. Thank you! 

(I think this issue can be closed.)
