### ISSUE TITLE
[Feature Request] MintNFT should return the NFT ID with the TransactionReceipt and/or Transaction

### ISSUE THREAD

**Issue by kdzapp** [matter-labs/zksync#314]
Relatively self explanatory but in order to minimize latency we store data associated with the NFT in our backend. It would be useful if on mint we had the id so we could later simply call `getNFT(nft_id)` if we wanted to truth check with zkSync any info about the NFT.

**Comment by adrianchifor** [comment]
You can use `nft_id_by_tx_hash`
