### ISSUE TITLE
Typescript SDK (BETA): Could not find a declaration file for module 'zksync'.

### ISSUE THREAD

**Issue by samsends** [matter-labs/zksync#315]
When trying to use the beta release (^0.11.0-beta.2) of the SDK I get an error regarding a missing type declaration file!

<img width="1088" alt="Screen Shot 2021-06-01 at 11 37 07 PM" src="https://user-images.githubusercontent.com/21231577/120420390-49456d80-c332-11eb-8341-9b65f8fe3fb7.png">

**Comment by StanislavBreadless** [comment]
Hi @samsends 

The issue was fixed in the latest `@beta` version. Please re-open the issue if it persists
