### ISSUE TITLE
Royalties for NFTs

### ISSUE THREAD

**Issue by sherodtaylor** [matter-labs/zksync#317]
Is there going to be a way to support royalties for NFT's? 

I know that https://eips.ethereum.org/EIPS/eip-2981 is still in the draft but I'm curious how I would implement that in this layer 2 solution or if there is any plan for it?

**Comment by StanislavBreadless** [comment]
Hi @sherodtaylor! We are sorry for the late reply :(

I just saw that the standard implies that the royalty is voluntary. If this is the case, then the best way for it would be to create a batch of two transactions: the one which swaps the nfts for some other token and the one which actually pays the royalty. More details can be found here: https://zksync.io/api/sdk/js/accounts.html#batch-builder

**Comment by sherodtaylor** [comment]
ah okay nice! Thank you @StanislavBreadless
