### ISSUE TITLE
SDK request Golang

### ISSUE THREAD

**Issue by sherodtaylor** [matter-labs/zksync#318]
I think that a golang sdk library would be nice

**Comment by StanislavBreadless** [comment]
Hi @sherodtaylor 

We are planning to make one, though can not give any ETAs yet

**Comment by tshabs** [comment]
@StanislavBreadless Is this something you would be interested in outsourcing? (we've slowed down much of our other work in anticipation of zkSync 2 release)

**Comment by StanislavBreadless** [comment]
@tshabs Actually all the SDK development (besides JS and Rust SDKs) are outsourced already :)
