### ISSUE TITLE
zk init fails

### ISSUE THREAD

**Issue by julianlen** [matter-labs/zksync#322]
Hi, when I run `zk init`, in the last step this happens:

```
[100%] Built target wasm-opt
wasm2js(38848,0x114345e00) malloc: *** error for object 0x7fd9b7820000: pointer being freed was not allocated
wasm2js(38848,0x114345e00) malloc: *** set a breakpoint in malloc_error_break to debug
./build.sh: line 24: 38848 Abort trap: 6           ../binaryen/bin/wasm2js ./dist/zksync-crypto-bundler_bg.wasm -o $ASM
```

Another prove I did:

within the `sdk/binaryen` folder, run: 

`python3 check.py`

```
[ checking wasm-opt -o notation... ]

executing:  /Users/julian/workspace/rskj-projects/zk/zksync/sdk/binaryen/bin/wasm-opt /Users/julian/workspace/rskj-projects/zk/zksync/sdk/binaryen/test/hello_world.wat -o a.wat -S
warning: no passes specified, not doing any work
wasm-opt(39600,0x1062f5e00) malloc: *** error for object 0x7f92b1c0ab60: pointer being freed was not allocated
wasm-opt(39600,0x1062f5e00) malloc: *** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
```

Here my clang version:
```
clang --version
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```
gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

The OS is MacOS Big Sur 11.5.1

```
(lldb) target create "bin/wasm-opt"
Current executable set to '/Users/julian/workspace/rskj-projects/zk/zksync/sdk/binaryen/bin/wasm-opt' (x86_64).
(lldb) b malloc_error_break
Breakpoint 1: where = libsystem_malloc.dylib`malloc_error_break, address = 0x00007fff2014f9ab
(lldb) run test/hello_world.wat -o a.wat -S
Process 5197 launched: '/Users/julian/workspace/rskj-projects/zk/zksync/sdk/binaryen/bin/wasm-opt' (x86_64)
warning: no passes specified, not doing any work
wasm-opt(5197,0x100920e00) malloc: *** error for object 0x107015e00: pointer being freed was not allocated
wasm-opt(5197,0x100920e00) malloc: *** set a breakpoint in malloc_error_break to debug
Process 5197 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x00007fff2034b9ab libsystem_malloc.dylib`malloc_error_break
libsystem_malloc.dylib`malloc_error_break:
->  0x7fff2034b9ab <+0>: pushq  %rbp
    0x7fff2034b9ac <+1>: movq   %rsp, %rbp
    0x7fff2034b9af <+4>: nop
    0x7fff2034b9b0 <+5>: nopl   (%rax)
Target 0: (wasm-opt) stopped.
```

**Comment by gosgos11** [comment]
I meet another error when run ./zk init

/mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/wasm-type.h:538:12: error: 'hash' defined as a class template here but previously declared as a
      struct template [-Werror,-Wmismatched-tags]
template<> class hash<wasm::Rtt> {
           ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/system_error:134:5: note: did you mean class here?
    struct hash;
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_bvector.h:548:31: note: did you mean class here?
    template<typename> friend struct hash;
                              ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/functional_hash.h:58:5: note: did you mean class here?
    struct hash;
    ^
8 errors generated.
src/ir/CMakeFiles/ir.dir/build.make:101: recipe for target 'src/ir/CMakeFiles/ir.dir/ReFinalize.cpp.o' failed
make[2]: *** [src/ir/CMakeFiles/ir.dir/ReFinalize.cpp.o] Error 1
CMakeFiles/Makefile2:504: recipe for target 'src/ir/CMakeFiles/ir.dir/all' failed

Here my env version:
os: ubuntu 16.04

clang: 
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

gcc: 
gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by StanislavBreadless** [comment]
> I meet another error when run ./zk init
> 
> /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/wasm-type.h:538:12: error: 'hash' defined as a class template here but previously declared as a
> struct template [-Werror,-Wmismatched-tags]
> template<> class hashwasm::Rtt {
> ^
> /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/system_error:134:5: note: did you mean class here?
> struct hash;
> ^
> /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_bvector.h:548:31: note: did you mean class here?
> template friend struct hash;
> ^
> /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/functional_hash.h:58:5: note: did you mean class here?
> struct hash;
> ^
> 8 errors generated.
> src/ir/CMakeFiles/ir.dir/build.make:101: recipe for target 'src/ir/CMakeFiles/ir.dir/ReFinalize.cpp.o' failed
> make[2]: *** [src/ir/CMakeFiles/ir.dir/ReFinalize.cpp.o] Error 1
> CMakeFiles/Makefile2:504: recipe for target 'src/ir/CMakeFiles/ir.dir/all' failed
> 
> Here my env version:
> os: ubuntu 16.04
> 
> clang:
> clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin
> 
> gcc:
> gcc --version
> gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions. There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Hi! Thank you for reaching out. On my PC:

```
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

```
clang version 10.0.0 (git@github.com:apple/llvm-project.git 3093af41dd65ad466dcd5603e9289244edfee4f5)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

Could you please try installing the same versions as on my PC?

**Comment by julianlen** [comment]
Solved (again),  what I did was the following:
1. Uninstalled rust `rustup self uninstall`
2. Uninstalled [xcode](https://dzone.com/articles/how-to-completely-uninstall-xcode-from-mac)
3. Uninstalled cmake `brew uninstall cmake`
4. Looked if I had another version of LLVM installed and I found that it was installed through Brew so I ran `brew uninstall llvm`.

Then, I reinstalled rust, xcode and cmake and when I ran `bin/wasm-opt test/hello_world.wat -o a.wat -S` again there were no errors.

**Comment by gosgos11** [comment]
> > I meet another error when run ./zk init
> > /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/wasm-type.h:538:12: error: 'hash' defined as a class template here but previously declared as a
> > struct template [-Werror,-Wmismatched-tags]
> > template<> class hashwasm::Rtt {
> > ^
> > /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/system_error:134:5: note: did you mean class here?
> > struct hash;
> > ^
> > /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_bvector.h:548:31: note: did you mean class here?
> > template friend struct hash;
> > ^
> > /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/functional_hash.h:58:5: note: did you mean class here?
> > struct hash;
> > ^
> > 8 errors generated.
> > src/ir/CMakeFiles/ir.dir/build.make:101: recipe for target 'src/ir/CMakeFiles/ir.dir/ReFinalize.cpp.o' failed
> > make[2]: *** [src/ir/CMakeFiles/ir.dir/ReFinalize.cpp.o] Error 1
> > CMakeFiles/Makefile2:504: recipe for target 'src/ir/CMakeFiles/ir.dir/all' failed
> > Here my env version:
> > os: ubuntu 16.04
> > clang:
> > clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
> > Target: x86_64-pc-linux-gnu
> > Thread model: posix
> > InstalledDir: /usr/bin
> > gcc:
> > gcc --version
> > gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
> > Copyright (C) 2015 Free Software Foundation, Inc.
> > This is free software; see the source for copying conditions. There is NO
> > warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> Hi! Thank you for reaching out. On my PC:
> 
> ```
> gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
> ```
> 
> ```
> clang version 10.0.0 (git@github.com:apple/llvm-project.git 3093af41dd65ad466dcd5603e9289244edfee4f5)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> ```
> 
> Could you please try installing the same versions as on my PC?

Thanks for your reply, I change gcc from 9.4 to 7.5, there is another error:

-- Build files have been written to: /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen
[  0%] Building CXX object src/ir/CMakeFiles/ir.dir/module-splitting.cpp.o
[  1%] Built target asmjs
[  1%] Building CXX object src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/optimizer-shared.cpp.o
[  2%] Built target cfg
[ 35%] Built target llvm_dwarf
[ 36%] Building CXX object src/passes/CMakeFiles/passes.dir/Print.cpp.o
[ 37%] Building CXX object src/passes/CMakeFiles/passes.dir/RoundTrip.cpp.o
/mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/emscripten-optimizer/optimizer-shared.cpp:208:11: error: unknown attribute 'fallthrough' ignored
      [-Werror,-Wunknown-attributes]
        [[fallthrough]];
          ^
/mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/emscripten-optimizer/optimizer-shared.cpp:210:7: error: unannotated fall-through between switch
      labels [-Werror,-Wimplicit-fallthrough]
      case '|':
      ^
/mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/emscripten-optimizer/optimizer-shared.cpp:210:7: note: insert '[[clang::fallthrough]];' to silence
      this warning
      case '|':
      ^
      [[clang::fallthrough]]; 
/mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/emscripten-optimizer/optimizer-shared.cpp:210:7: note: insert 'break;' to avoid fall-through
      case '|':
      ^
      break; 
2 errors generated.
src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/build.make:62: recipe for target 'src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/optimizer-shared.cpp.o' failed
make[2]: *** [src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/optimizer-shared.cpp.o] Error 1
CMakeFiles/Makefile2:669: recipe for target 'src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/all' failed
make[1]: *** [src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 38%] Building CXX object src/passes/CMakeFiles/passes.dir/StackIR.cpp.o
/mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/ir/module-splitting.cpp:615:10: error: moving a temporary object prevents copy elision
      [-Werror,-Wpessimizing-move]
  return std::move(ModuleSplitter(primary, config).secondaryPtr);
         ^
/mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/ir/module-splitting.cpp:615:10: note: remove std::move call here
  return std::move(ModuleSplitter(primary, config).secondaryPtr);
         ^~~~~~~~~~                                            ~
/mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3056:11: error: unknown attribute 'fallthrough' ignored
      [-Werror,-Wunknown-attributes]
        [[fallthrough]];
          ^
/mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3068:11: error: unknown attribute 'fallthrough' ignored
      [-Werror,-Wunknown-attributes]
        [[fallthrough]];
          ^
/mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3057:7: error: unannotated fall-through between switch labels
      [-Werror,-Wimplicit-fallthrough]
      case StackInst::BlockBegin:
      ^
/mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3057:7: note: insert '[[clang::fallthrough]];' to silence this warning
      case StackInst::BlockBegin:
      ^
      [[clang::fallthrough]]; 
/mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3057:7: note: insert 'break;' to avoid fall-through
      case StackInst::BlockBegin:
      ^
      break; 
/mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3069:7: error: unannotated fall-through between switch labels
      [-Werror,-Wimplicit-fallthrough]
      case StackInst::BlockEnd:
      ^
/mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3069:7: note: insert '[[clang::fallthrough]];' to silence this warning
      case StackInst::BlockEnd:
      ^
      [[clang::fallthrough]]; 
/mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3069:7: note: insert 'break;' to avoid fall-through
      case StackInst::BlockEnd:
      ^
      break; 
1 error generated.
src/ir/CMakeFiles/ir.dir/build.make:127: recipe for target 'src/ir/CMakeFiles/ir.dir/module-splitting.cpp.o' failed
make[2]: *** [src/ir/CMakeFiles/ir.dir/module-splitting.cpp.o] Error 1
CMakeFiles/Makefile2:504: recipe for target 'src/ir/CMakeFiles/ir.dir/all' failed
make[1]: *** [src/ir/CMakeFiles/ir.dir/all] Error 2
[ 38%] Building CXX object src/passes/CMakeFiles/passes.dir/Strip.cpp.o
[ 39%] Building CXX object src/passes/CMakeFiles/passes.dir/StripTargetFeatures.cpp.o
4 errors generated.
src/passes/CMakeFiles/passes.dir/build.make:652: recipe for target 'src/passes/CMakeFiles/passes.dir/Print.cpp.o' failed
make[2]: *** [src/passes/CMakeFiles/passes.dir/Print.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:724: recipe for target 'src/passes/CMakeFiles/passes.dir/all' failed
make[1]: *** [src/passes/CMakeFiles/passes.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 2

**Comment by StanislavBreadless** [comment]
> > > I meet another error when run ./zk init
> > > /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/wasm-type.h:538:12: error: 'hash' defined as a class template here but previously declared as a
> > > struct template [-Werror,-Wmismatched-tags]
> > > template<> class hashwasm::Rtt {
> > > ^
> > > /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/system_error:134:5: note: did you mean class here?
> > > struct hash;
> > > ^
> > > /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_bvector.h:548:31: note: did you mean class here?
> > > template friend struct hash;
> > > ^
> > > /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/functional_hash.h:58:5: note: did you mean class here?
> > > struct hash;
> > > ^
> > > 8 errors generated.
> > > src/ir/CMakeFiles/ir.dir/build.make:101: recipe for target 'src/ir/CMakeFiles/ir.dir/ReFinalize.cpp.o' failed
> > > make[2]: *** [src/ir/CMakeFiles/ir.dir/ReFinalize.cpp.o] Error 1
> > > CMakeFiles/Makefile2:504: recipe for target 'src/ir/CMakeFiles/ir.dir/all' failed
> > > Here my env version:
> > > os: ubuntu 16.04
> > > clang:
> > > clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
> > > Target: x86_64-pc-linux-gnu
> > > Thread model: posix
> > > InstalledDir: /usr/bin
> > > gcc:
> > > gcc --version
> > > gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
> > > Copyright (C) 2015 Free Software Foundation, Inc.
> > > This is free software; see the source for copying conditions. There is NO
> > > warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> > 
> > 
> > Hi! Thank you for reaching out. On my PC:
> > ```
> > gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > clang version 10.0.0 (git@github.com:apple/llvm-project.git 3093af41dd65ad466dcd5603e9289244edfee4f5)
> > Target: x86_64-unknown-linux-gnu
> > Thread model: posix
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you please try installing the same versions as on my PC?
> 
> Thanks for your reply, I change gcc from 5.5 to 7.5, there is another error:
> 
> -- Build files have been written to: /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen
> [ 0%] Building CXX object src/ir/CMakeFiles/ir.dir/module-splitting.cpp.o
> [ 1%] Built target asmjs
> [ 1%] Building CXX object src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/optimizer-shared.cpp.o
> [ 2%] Built target cfg
> [ 35%] Built target llvm_dwarf
> [ 36%] Building CXX object src/passes/CMakeFiles/passes.dir/Print.cpp.o
> [ 37%] Building CXX object src/passes/CMakeFiles/passes.dir/RoundTrip.cpp.o
> /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/emscripten-optimizer/optimizer-shared.cpp:208:11: error: unknown attribute 'fallthrough' ignored
> [-Werror,-Wunknown-attributes]
> [[fallthrough]];
> ^
> /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/emscripten-optimizer/optimizer-shared.cpp:210:7: error: unannotated fall-through between switch
> labels [-Werror,-Wimplicit-fallthrough]
> case '|':
> ^
> /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/emscripten-optimizer/optimizer-shared.cpp:210:7: note: insert '[[clang::fallthrough]];' to silence
> this warning
> case '|':
> ^
> [[clang::fallthrough]];
> /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/emscripten-optimizer/optimizer-shared.cpp:210:7: note: insert 'break;' to avoid fall-through
> case '|':
> ^
> break;
> 2 errors generated.
> src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/build.make:62: recipe for target 'src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/optimizer-shared.cpp.o' failed
> make[2]: *** [src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/optimizer-shared.cpp.o] Error 1
> CMakeFiles/Makefile2:669: recipe for target 'src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/all' failed
> make[1]: *** [src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 38%] Building CXX object src/passes/CMakeFiles/passes.dir/StackIR.cpp.o
> /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/ir/module-splitting.cpp:615:10: error: moving a temporary object prevents copy elision
> [-Werror,-Wpessimizing-move]
> return std::move(ModuleSplitter(primary, config).secondaryPtr);
> ^
> /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/ir/module-splitting.cpp:615:10: note: remove std::move call here
> return std::move(ModuleSplitter(primary, config).secondaryPtr);
> ^~~~~~~~~~ ~
> /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3056:11: error: unknown attribute 'fallthrough' ignored
> [-Werror,-Wunknown-attributes]
> [[fallthrough]];
> ^
> /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3068:11: error: unknown attribute 'fallthrough' ignored
> [-Werror,-Wunknown-attributes]
> [[fallthrough]];
> ^
> /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3057:7: error: unannotated fall-through between switch labels
> [-Werror,-Wimplicit-fallthrough]
> case StackInst::BlockBegin:
> ^
> /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3057:7: note: insert '[[clang::fallthrough]];' to silence this warning
> case StackInst::BlockBegin:
> ^
> [[clang::fallthrough]];
> /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3057:7: note: insert 'break;' to avoid fall-through
> case StackInst::BlockBegin:
> ^
> break;
> /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3069:7: error: unannotated fall-through between switch labels
> [-Werror,-Wimplicit-fallthrough]
> case StackInst::BlockEnd:
> ^
> /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3069:7: note: insert '[[clang::fallthrough]];' to silence this warning
> case StackInst::BlockEnd:
> ^
> [[clang::fallthrough]];
> /mnt/docker-root/dockerapp/zksync/zksync/sdk/binaryen/src/passes/Print.cpp:3069:7: note: insert 'break;' to avoid fall-through
> case StackInst::BlockEnd:
> ^
> break;
> 1 error generated.
> src/ir/CMakeFiles/ir.dir/build.make:127: recipe for target 'src/ir/CMakeFiles/ir.dir/module-splitting.cpp.o' failed
> make[2]: *** [src/ir/CMakeFiles/ir.dir/module-splitting.cpp.o] Error 1
> CMakeFiles/Makefile2:504: recipe for target 'src/ir/CMakeFiles/ir.dir/all' failed
> make[1]: *** [src/ir/CMakeFiles/ir.dir/all] Error 2
> [ 38%] Building CXX object src/passes/CMakeFiles/passes.dir/Strip.cpp.o
> [ 39%] Building CXX object src/passes/CMakeFiles/passes.dir/StripTargetFeatures.cpp.o
> 4 errors generated.
> src/passes/CMakeFiles/passes.dir/build.make:652: recipe for target 'src/passes/CMakeFiles/passes.dir/Print.cpp.o' failed
> make[2]: *** [src/passes/CMakeFiles/passes.dir/Print.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> CMakeFiles/Makefile2:724: recipe for target 'src/passes/CMakeFiles/passes.dir/all' failed
> make[1]: *** [src/passes/CMakeFiles/passes.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> error Command failed.
> Exit code: 2

Maybe try doing the same as @gosgos11 did? Reinstalling as much dev stuff as possible

**Comment by gosgos11** [comment]
I change OS to ubuntu 20.04 and compile successfully.
OS: ubuntu 20.04
gcc: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
clang:  clang version 10.0.0-4ubuntu1
rustc: rustc 1.54.0 (a178d0322 2021-07-26)
