### ISSUE TITLE
`vlog` can be blocking

### ISSUE THREAD

**Issue by HAOYUatHZ** [matter-labs/zksync#324]
As discussed in https://github.com/Fluidex/dingir-exchange/issues/115 (credits to @driftluo from @nervosnetwork & @silathdiir from @Fluidex), 

https://github.com/matter-labs/zksync/blob/master/core/lib/vlog/src/lib.rs uses `tracing_subscriber::fmt::Subscriber`, whose default writer is blocking.

Suggest changing to a style like https://github.com/Fluidex/dingir-exchange/pull/185/files

**Comment by popzxc** [comment]
Thanks! @Deniallugo and @StanislavBreadless please look into it.
