### ISSUE TITLE
how to get docker/geth genesis address private key to transfer test ETH?

### ISSUE THREAD

**Issue by gosgos11** [matter-labs/zksync#327]
Run local geth use docker with https://github.com/matter-labs/zksync/tree/master/docker/geth ，what's password of the keystore  file, the password.sec is null. how to transfer local test ETH?

**Comment by StanislavBreadless** [comment]
@gosgos11 You can do `zk run test-accounts`

**Comment by gosgos11** [comment]
> @gosgos11 You can do `zk run test-accounts`

Thank you, I get the private key, and test deposit and transfer ETH, that's great.
