### ISSUE TITLE
explorer compile error: use yarn run serve or yarn run build

### ISSUE THREAD

**Issue by gosgos11** [matter-labs/zksync#328]
zksync/infrastructure/explorer# yarn run serve
yarn run v1.22.11
$ yarn copy_config && vue-cli-service serve --port=7000
$ cp ../../etc/js/env-config.js src/
 INFO  Starting development server...
40% building 109/136 modules 27 active ...ure/explorer/node_modules/url/util.jsBrowserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                               11:30:21 AM

 error  in /alidata/work/zksync/node_modules/zksync-crypto/dist/zksync-crypto-web.js

Module parse failed: Unexpected token (313:59)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| async function init(input) {
|     if (typeof input === 'undefined') {
>         input = new URL('zksync-crypto-web_bg.wasm', import.meta.url);
|     }
|     const imports = {};

 @ /alidata/work/zksync/node_modules/zksync/build/crypto.js 32:25-49
 @ /alidata/work/zksync/node_modules/zksync/build/index.js
 @ ./src/utils.js
 @ ./src/store.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.6.128:7000&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by StanislavBreadless** [comment]
@gosgos11 @popzxc We don't use the explorer from the repo anymore, so I guess we should drop its support and remove it from the repo

**Comment by gosgos11** [comment]
> @gosgos11 @popzxc We don't use the explorer from the repo anymore, so I guess we should drop its support and remove it from the repo

Thank you reply so quick, now  which explorer uesed?

**Comment by StanislavBreadless** [comment]
> > @gosgos11 @popzxc We don't use the explorer from the repo anymore, so I guess we should drop its support and remove it from the repo
> 
> Thank you reply so quick, now which explorer uesed?
> 
> I find the explorer https://zkscan.io/, does it open source?

Not yet, but we'll opensource it very soon

**Comment by IversonHan** [comment]
I met the same mistake. Did you solve it later?

**Comment by IversonHan** [comment]
> zksync/infrastructure/explorer# yarn run serve yarn run v1.22.11 $ yarn copy_config && vue-cli-service serve --port=7000 $ cp ../../etc/js/env-config.js src/ INFO Starting development server... 40% building 109/136 modules 27 active ...ure/explorer/node_modules/url/util.jsBrowserslist: caniuse-lite is outdated. Please run: npx browserslist@latest --update-db
> 
> Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating 98% after emitting CopyPlugin
> 
> ERROR Failed to compile with 1 error 11:30:21 AM
> 
> error in /alidata/work/zksync/node_modules/zksync-crypto/dist/zksync-crypto-web.js
> 
> Module parse failed: Unexpected token (313:59) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders | async function init(input) { | if (typeof input === 'undefined') {
> 
> > ```
> >     input = new URL('zksync-crypto-web_bg.wasm', import.meta.url);
> > ```
> 
> | } | const imports = {};
> 
> @ /alidata/work/zksync/node_modules/zksync/build/crypto.js 32:25-49 @ /alidata/work/zksync/node_modules/zksync/build/index.js @ ./src/utils.js @ ./src/store.js @ ./src/main.js @ multi (webpack)-dev-server/client?http://192.168.6.128:7000&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

I wonder if you have solved this problem? I forked this project, and i copied the explorer, i can run the explorer normaly when i changed something in node_modules. I can help you if you need.
