### ISSUE TITLE
witness_gen  load_account_tree logic bug.

### ISSUE THREAD

**Issue by yaanhyy** [matter-labs/zksync#329]
witness_generator use   load_account_tree function to reconstruct account tree. it prefer use  cache state to save cpu. But it load committed_state use last block on 
https://github.com/matter-labs/zksync/blob/64cdd58c9b36bf16a64dec08f06c8807c9e86387/core/bin/zksync_witness_generator/src/witness_generator.rs#L114
I think it should use cached_block.

**Comment by popzxc** [comment]
Sorry for the long response. We can use `cached_block` here indeed, but it won't change the stuff much.
This function is a subject for a bigger refactoring and we plan to rewrite it soon.
