### ISSUE TITLE
Error: Request failed with status code 400

### ISSUE THREAD

**Issue by aliveli186** [matter-labs/zksync#339]
What could be the reason of that error?
Rate limit? If so what is that limit?

```
data: '{"id":1,"jsonrpc":"2.0","method":"tx_info","params":["sync-tx:a33b8e88e29447cd10bcd47039f7fb30dad417c809803ce5d072304a50af1269"]}',
headers: {
  Accept: 'application/json, text/plain, */*',
  'Content-Type': 'application/json',
  'User-Agent': 'axios/0.21.4',
  'Content-Length': 129
}
```

**Comment by StanislavBreadless** [comment]
Hi @aliveli186! We are sorry for the late response :(

Could you please provide what network are you using? Just tried out the request on mainnet, worked well on my side

**Comment by aliveli186** [comment]
@StanislavBreadless It happens on mainnet. Not every time, sometimes.
I increased polling from 1000 ms to 2000 ms but it didn't make a difference, still happens.

**Comment by StanislavBreadless** [comment]
> @StanislavBreadless It happens on mainnet. Not every time, sometimes. I increased polling from 1000 ms to 2000 ms but it didn't make a difference, still happens.

There is a known problem with attempting to wait for the verification of a deposit. Could you please provide code snippets that reproduce the error?
