### ISSUE TITLE
Add an illustration to the tutorial on the testnet

### ISSUE THREAD

**Issue by silentwars** [matter-labs/zksync#341]
**Is your feature request related to a problem? Please describe.**
When I used the testnet, I switched Metamask to Rinkeby (experienced users thought that would be fine), but I couldn’t connect to zksync. I checked the tutorial. Since I was an experienced user, I ignored the ether in the bottom right corner. The icon switch of the square caused the testnet to be unavailable all the time, which took a lot of time. At the same time, I also found that many users have similar situations on discord.

**Describe the solution you'd like**
By adding pictures or other hints to the tutorial

**Describe alternatives you've considered**
Add a screenshot of the Ethereum icon in the lower right corner. Change the prompt to switch Rinkeby in a prominent place in the tutorial or test page.

**Additional context**
![sr](https://user-images.githubusercontent.com/22576479/140741974-91c7ec06-a87e-4edf-bf43-92b15db87626.png)
![23](https://user-images.githubusercontent.com/22576479/140741989-f3f4b1ed-34b5-4d05-b617-1c1a739957e9.png)

**Comment by Jejda** [comment]
good idea

**Comment by bxpana** [comment]
Resolved, thanks for the feedback https://docs.zksync.io/userdocs/tutorials.html#add-funds-to-zksync-with-metamask
