### ISSUE TITLE
Feedback about an address that needs to be activated multiple times to use the transfer and mint nft functions

### ISSUE THREAD

**Issue by age-wang** [matter-labs/zksync#344]
I often use the zksync network for transfers and mint nft, but I found that in the past few months, the system will require me to activate my account multiple times to use the transfer function. This is different from the advertised account that only needs to be activated once.
I hope to check out what caused this error
My address is 0x6eCe332E1324FB0C080a6364e84171EEc1571f5f
thank you very much

**Comment by StanislavBreadless** [comment]
Hi @age-wang!We are sorry for the inconvenience :( Is the issue on https://wallet.zksync.io/?

**Comment by age-wang** [comment]
> 嗨@age-wang！对于给您带来的不便，我们深表意意:( https://wallet.zksync.io/上有问题吗？

Yes, I used the metamask wallet to log in at https://wallet.zksync.io/.

**Comment by StanislavBreadless** [comment]
@age-wang There was a similar issue connected to zknft.xyz. Maybe you used this tool?

Please note that the wallet most likely asks you only for authorization of the transfer and not for an unlock

**Comment by age-wang** [comment]
> @age-wang There was a similar issue connected to zknft.xyz. Maybe you used this tool?
> 
> Please note that the wallet most likely asks you only for authorization of the transfer and not for an unlock

Yes, I have used zknft.xyz,       but you can check the record of my address, which shows that it is not authorization but Account activation
My address is 0x6eCe332E1324FB0C080a6364e84171EEc1571f5f

**Comment by StanislavBreadless** [comment]
@age-wang It is a known old issue. We are sorry for the problems. The Account activation was removed from zknft to avoid such errors in the future

**Comment by age-wang** [comment]
> @age-wang It is a known old issue. We are sorry for the problems. The Account activation was removed from zknft to avoid such errors in the future

It’s good to solve it, because the feedback has not been confirmed before, so I propose it again on GitHub. Thank you very much for your patience.
