### ISSUE TITLE
Java SDK for zksync

### ISSUE THREAD

**Issue by berryjam** [matter-labs/zksync#345]
It will be useful to release Java SDK to help more people engage in zksync given a large number of Java developers and projects.

**Comment by StanislavBreadless** [comment]
We already have [one](https://zksync.io/api/sdk/java/). We would love to hear your feedback on it

https://github.com/zksync-sdk/zksync-java

**Comment by berryjam** [comment]
> 

Thanks for your reply,I found all the SDK in zksync-sdk group.
