### ISSUE TITLE
zkSync 500 error while try to get fauset drop

### ISSUE THREAD

**Issue by pringlzkur** [matter-labs/zksync#350]
Hi Guys! 
Please take a look at this issue
1) login with metamask
2) set rinkeby zkSync chain
3) try to tweet 
4) made a tweet successfully
5) wait for fauset drop
6) no drop - 500 error on console
`https://stage2-faucet.zksync.dev/ask_money`  500 error with huge delay

![image](https://user-images.githubusercontent.com/25226714/144602419-90943350-1fee-455e-9467-9662682b6a6a.png)

**Comment by mderazon** [comment]
Reproduces for me 100% of times as well. Not sure what the problem is as 500 error is not descriptive. Can post more details if needed

**Comment by adrianchifor** [comment]
@pringlzkur We believe this is now resolved, are you still seeing it?
