### ISSUE TITLE
zk prover failed

### ISSUE THREAD

**Issue by IversonHan** [matter-labs/zksync#354]
I started the zk server and eth nodes normally, but zk prover kept reporting errors while aggregating proofs.It looks like:
```
Recursive circuit proof is invalid
```
Then, I change the command to 'zk prover 3', it doesn't work.

**Comment by adrianchifor** [comment]
Hey @IversonHan, is this still the case? we could not replicate it locally

**Comment by IversonHan** [comment]
> Hey @IversonHan, is this still the case? we could not replicate it locally

Well, it's a long time ago, it does not matter anymore.I will close thie issue.Thanks.
