### ISSUE TITLE
zk init  error

### ISSUE THREAD

**Issue by zu19890223** [matter-labs/zksync#362]
when i run zk init, i found an error "Failed opening './dist/zksync-crypto-bundler_bg.wasm'"

logs:
Pulling postgres                    ... done
Pulling geth                        ... done
Pulling dev-liquidity-token-watcher ... done
Pulling dev-ticker                  ... done
Pulling tesseracts                  ... done
Pulling elastic                     ... done
Starting zksync_dev-liquidity-token-watcher_1 ...
zksync_geth_1 is up-to-date
zksync_postgres_1 is up-to-date
Starting zksync_dev-liquidity-token-watcher_1 ... done
zksync_tesseracts_1 is up-to-date
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.67s.
yarn run v1.22.17
$ yarn workspace zksync-crypto build
warning package.json: No license field
$ ./build.sh && node web-wasm.js
/Users/xxx/.cargo/bin/wasm-pack
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
    Finished release [optimized] target(s) in 0.10s
[WARN]: ⚠️   origin crate has no README
[INFO]: License key is set in Cargo.toml but no LICENSE file(s) were found; Please add the LICENSE file(s) to your project directory
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional field missing from Cargo.toml: 'description'. This is not necessary, but recommended
[INFO]: ✨   Done in 0.91s
[INFO]: 📦   Your wasm pkg is ready to publish at /Users/xxx/work/zksync/sdk/zksync-crypto/dist.
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
    Finished release [optimized] target(s) in 0.06s
[WARN]: ⚠️   origin crate has no README
[INFO]: License key is set in Cargo.toml but no LICENSE file(s) were found; Please add the LICENSE file(s) to your project directory
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional field missing from Cargo.toml: 'description'. This is not necessary, but recommended
[INFO]: ✨   Done in 0.78s
[INFO]: 📦   Your wasm pkg is ready to publish at /Users/xxx/work/zksync/sdk/zksync-crypto/dist.
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
    Finished release [optimized] target(s) in 0.06s
[WARN]: ⚠️   origin crate has no README
[INFO]: License key is set in Cargo.toml but no LICENSE file(s) were found; Please add the LICENSE file(s) to your project directory
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional field missing from Cargo.toml: 'description'. This is not necessary, but recommended
[INFO]: ✨   Done in 0.79s
[INFO]: 📦   Your wasm pkg is ready to publish at /Users/xxx/work/zksync/sdk/zksync-crypto/dist.
-- Building with -DBUILD_LLVM_DWARF
-- Building with -std=c++14
-- Building with -Wall
-- Building with -Werror
-- Building with -Wextra
-- Building with -Wno-unused-parameter
-- Building with -fno-omit-frame-pointer
-- Building with -fno-rtti
-- Building with -Wno-implicit-int-float-conversion
-- Building with -Wno-unknown-warning-option
-- Building with -Wswitch
-- Building with -Wimplicit-fallthrough
-- Building with -Wnon-virtual-dtor
-- Building with -fPIC
-- Building with -O0
-- Building with -g3
-- Building libbinaryen as shared library.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/xxx/work/zksync/sdk/binaryen
Consolidate compiler generated dependencies of target cfg
Consolidate compiler generated dependencies of target asmjs
Consolidate compiler generated dependencies of target emscripten-optimizer
Consolidate compiler generated dependencies of target support
Consolidate compiler generated dependencies of target ir
Consolidate compiler generated dependencies of target wasm
[  0%] Built target cfg
[  1%] Built target asmjs
[  3%] Built target emscripten-optimizer
Consolidate compiler generated dependencies of target llvm_dwarf
[  8%] Built target support
[ 13%] Built target ir
Consolidate compiler generated dependencies of target passes
[ 19%] Built target wasm
[ 49%] Built target llvm_dwarf
[ 88%] Built target passes
Consolidate compiler generated dependencies of target binaryen
[ 89%] Built target binaryen
Consolidate compiler generated dependencies of target wasm-opt
Consolidate compiler generated dependencies of target wasm-emscripten-finalize
Consolidate compiler generated dependencies of target wasm-shell
Consolidate compiler generated dependencies of target wasm2js
Consolidate compiler generated dependencies of target wasm-metadce
Consolidate compiler generated dependencies of target wasm-dis
Consolidate compiler generated dependencies of target wasm-as
Consolidate compiler generated dependencies of target wasm-ctor-eval
[ 91%] Built target wasm-emscripten-finalize
[ 91%] Built target wasm-shell
[ 92%] Built target wasm-metadce
[ 93%] Built target wasm2js
[ 95%] Built target wasm-dis
[ 95%] Built target wasm-opt
[ 96%] Built target wasm-ctor-eval
[ 97%] Built target wasm-as
Consolidate compiler generated dependencies of target wasm-reduce
Consolidate compiler generated dependencies of target wasm-split
[ 98%] Built target wasm-reduce
[100%] Built target wasm-split
Failed opening './dist/zksync-crypto-bundler_bg.wasm'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1

i want to know how to fix it .  thx.

**Comment by cleathers** [comment]
Same error here.

**Comment by cleathers** [comment]
@adrianchifor, I was running into the same issue. I had to uninstall wasm-pack and reinstall wasm-pack like mentioned in this MR
https://github.com/matter-labs/zksync/pull/358

**Comment by adrianchifor** [comment]
Cool, thanks for confirming! Merged #358 so will close this one
