### ISSUE TITLE
A question about revertBlocks 

### ISSUE THREAD

**Issue by zhiqiangxu** [matter-labs/zksync#364]
There is a [revertBlocks](https://github.com/matter-labs/zksync/blob/c878015bc7ee126e9726b93337fd5eea772b91c2/contracts/contracts/AdditionalZkSync.sol#L195) to revert bad blocks, but it also introduces another problem IMO: it's public and even good blocks can be reverted, in theory byzantine parties can halt the progress of the protocol by revert good blocks continuously?

Is it a flaw of liveness or there's something else that I'm missing?

**Comment by adrianchifor** [comment]
Hey @zhiqiangxu, please see https://github.com/matter-labs/zksync/blob/5f47fe9990ec87e3087d32d083d13e6cab331ff1/docs/contract.md#reverting-expired-blocks and https://github.com/matter-labs/zksync/blob/f59e154865374bdc0f5ded2e2604dac599cb75ee/docs/protocol.md#revert-blocks for the explanation behind `revertBlocks`
