### ISSUE TITLE
Add Support for ( XDC ) Network.

### ISSUE THREAD

**Issue by RuslanWing** [matter-labs/zksync#366]
XinFin XDC.Network is an enterprise-ready hybrid Blockchain technology company optimised for international trade and finance. The XinFin XDC.network is powered by the native coin called XDC. The XDC protocol is architected to support smart contracts, 2000TPS, 2seconds transaction time, KYC to Masternodes (Validator Nodes). The XDC.Network uses XinFin Delegated Proof of Stake (XDPoS), with the intending to create a ‘highly-scalable, secure, permission, and commercial grade’ blockchain network.

Github:- https://github.com/XinFinOrg

CMC :- https://coinmarketcap.com/currencies/xinfin-network/

Docker FullNode:- https://github.com/xinfinorg/XinFin-Node

Technical Community Support available at:

Telegram Community: https://t.me/XinFinDevelopers

Slack Community: https://xinfin-public.slack.com/messages/CELR2M831/

Slack Invitation Link: https://launchpass.com/xinfin-public

Technical help Resource: http://howto.xinfin.org/

**Comment by adrianchifor** [comment]
Hey @RuslanWing, thanks for the details, we will take a look and consider it.
