### ISSUE TITLE
How does zkSync prevent replay attacks between networks?

### ISSUE THREAD

**Issue by xwartz** [matter-labs/zksync#368]
I found that zkSync does not use chainId when signing transactions, so how does zkSync prevent replay attacks?

Below is the signature message:
```ts
getTransferEthMessagePart(tx: {
    stringAmount: string;
    stringToken: string;
    stringFee: string;
    ethAddress?: string;
    to?: string;
}): string {
    let txType: string, to: string;
    if (tx.ethAddress != undefined) {
        txType = 'Withdraw';
        to = tx.ethAddress;
    } else if (tx.to != undefined) {
        txType = 'Transfer';
        to = tx.to;
    } else {
        throw new Error('Either to or ethAddress field must be present');
    }

    let message = '';
    if (tx.stringAmount != null) {
        message += `${txType} ${tx.stringAmount} ${tx.stringToken} to: ${to.toLowerCase()}`;
    }
    if (tx.stringFee != null) {
        if (message.length != 0) {
            message += '\n';
        }
        message += `Fee: ${tx.stringFee} ${tx.stringToken}`;
    }
    return message;
}
```

ref: https://github.com/matter-labs/zksync/blob/f59e154865374bdc0f5ded2e2604dac599cb75ee/sdk/zksync.js/src/eth-message-signer.ts#L210-L239

For example:
An attacker taking someone's testnet(zkSync-ropsten) transaction, and repeating it on the mainnet(zkSync-mainnet). How dose zkSync prevent it?

**Comment by bxpana** [comment]
Hi, that's a fair question. The way the private key is generated on zkSync is dependent of the network the wallet is connected to. So a user would end up with different keys for testnet and mainnet.
