### ISSUE TITLE
zkSync API response error: errorType: submitError; code 605; message: Transaction adding error: Eth signature is incorrect.

### ISSUE THREAD

**Issue by ihmcrypto** [matter-labs/zksync#370]
Hey guys, I'm getting this issue when I try to send funds to checkout a Gitcoin grant using Argent wallet.

<img width="677" alt="Screen Shot 2022-03-10 at 2 49 19 PM" src="https://user-images.githubusercontent.com/97023642/157606100-d8850ce3-4352-45a9-9bef-d8ec093d511e.png">

**Comment by ericp1337** [comment]
Were you able to get it working? I'm getting this same error message, but using Coinbase instead.
