### ISSUE TITLE
zksync 2.0 and zkevm source code

### ISSUE THREAD

**Issue by henry-hz** [matter-labs/zksync#374]
Dears, please, I would like to review the zksync 2.0 code and zkevm that was just launched on Goerli, but the only branch I found here was the V3, freezed 2 years ago.....

**Comment by StanislavBreadless** [comment]
Hey @henry-hz, the code for zkSync 2.0 is not open-sourced yet, but it will be open-sourced later

**Comment by FullyNonlinear** [comment]
> Hey @henry-hz, the code for zkSync 2.0 is not open-sourced yet, but it will be open-sourced later

I would like also to check my understanding that the front end for compiling EVM code into R1CS is also not open-sourced yet but included in zkSync 2.0?

(Very much looking forward to it by the way)
