### ISSUE TITLE
Avoid network change on MetaMask

### ISSUE THREAD

**Issue by Laurianti** [matter-labs/zksync#381]
Hello, I'm approaching to zkSync for the first time, and I have a question:
Is it possible to invoke write methods of a contract without changing the active network, and using directly the Ethereum Mainnet, on MetaMask?

In the greeter-tutorial-starter I can see this:
https://github.com/matter-labs/greeter-tutorial-starter/blob/master/src/App.vue#L163
This makes me believe that it isn't supported and if so, why?

Thank you

**Comment by bxpana** [comment]
One cannot submit a normal zksync transaction without changing the active network in Metamask. However, you can submit so-called "priority" operation this way: it will be stored in zksync L1 contract, our server will pick it up from there and execute. However, this is much more expensive, as you need to pay for L1 gas.
