### ISSUE TITLE
Interested in the Instant Confirmation Mechanism

### ISSUE THREAD

**Issue by SipengXie** [matter-labs/zksync#382]
Hello, I'm interested in the Instant Confirmation Mechanism, and want to know more details about it. Where can I get the doc or the code?
Waiting for your reply, thank you!

**Comment by SipengXie** [comment]
And I'm wondering why slashing the security bond of the intersection of the signers of the original receipts and the new block can ensure that only malicious users will be punished?

**Comment by SipengXie** [comment]
@huitseeker @alekseysidorov @rocketblr @gluk64  sorry to bother you guys. The knowledge is really important to me.

**Comment by bxpana** [comment]
@SipengXie This is about zkSync 2.0 correct?

**Comment by SipengXie** [comment]
@bxpana I found it in the document of zkSync 1.x
https://docs.zksync.io/userdocs/tech.html#instant-confirmations

**Comment by bxpana** [comment]
Ok, I'll see what I can find out from the team

**Comment by SipengXie** [comment]
@bxpana Thank you!

**Comment by bxpana** [comment]
> And I'm wondering why slashing the security bond of the intersection of the signers of the original receipts and the new block can ensure that only malicious users will be punished?

The basic idea is to punish the validators who falsely promised to include the tx in a block, but they did not

Designing a secure decentralized model for instant confirmation is no easy task. We are currently mostly focused on scalability, but we have decentralization on our long-term roadmap
