### ISSUE TITLE
question about source code

### ISSUE THREAD

**Issue by LuozhuZhang** [matter-labs/zksync#383]
I am reading the source code of matter-lab/zksync to understand it better and then join you guys to build this project.

But I have some questions.

I want to know which branch is more suitable for reading and learning, master branch or dev branch, can you tell me the difference between them?

Can you explain this to me?

And another issue, there is a few information about zksync source code, so I think the solution is to encourage more people write articles to explain how exactly zksync works

<img width="1344" alt="Screen Shot 2022-04-29 at 14 48 55" src="https://user-images.githubusercontent.com/70309026/165896917-2436cc72-662f-4c74-8c60-48211ca0eb85.png">

@popzxc @StanislavBreadless

**Comment by popzxc** [comment]
Hi! Thanks for your interest in zkSync.

This is a public mirror of the private development repository, so you can consider it to be a "snapshot" of the actual code that is being updated from time to time. We publish changes to the master branch normally. There is some information about source code architecture in the `docs` folder, for example [the architecture overview](https://github.com/matter-labs/zksync/blob/master/docs/architecture.md).

While we appreciate contributions, most of the development is being coordinated in the team internally, so keeping it in sync with the public repo may be hard at times. Additionally, most of our focus is on developing the 2.0 version right now.

That being said, being more open to the developer community is one of our focuses for the 2.0 -- I hope the processes will be better there.

**Comment by LuozhuZhang** [comment]
> Hi! Thanks for your interest in zkSync.
> 
> This is a public mirror of the private development repository, so you can consider it to be a "snapshot" of the actual code that is being updated from time to time. We publish changes to the master branch normally. There is some information about source code architecture in the `docs` folder, for example [the architecture overview](https://github.com/matter-labs/zksync/blob/master/docs/architecture.md).
> 
> While we appreciate contributions, most of the development is being coordinated in the team internally, so keeping it in sync with the public repo may be hard at times. Additionally, most of our focus is on developing the 2.0 version right now.
> 
> That being said, being more open to the developer community is one of our focuses for the 2.0 -- I hope the processes will be better there.

Thanks for the reply, it sounds like the dev branch is more stable and better to read.

I think there may be 1000+ rollups in the future, and many may be application-specific rollups, I think these rollups can be used as L3 deployed on zkSync L2.

So I want to develop a tool/protocol that is convenient for developers to write and deploy a rollup based on zkSync.

Can you review my idea and tell me what's missing.

**Comment by popzxc** [comment]
> Thanks for the reply, it sounds like the dev branch is more stable and better to read.

Actually, it just was not updated for a longer period of time. You can read and use it if you find it more convenient -- just keep in mind that it doesn't represent the current state of zkSync.

> Can you review my idea and tell me what's missing.

L3s are actually a hot topic right now, as well as limitless scalability in general. This sounds however that it would be more relevant for zkSync 2.0, since zkSync 1.0 is not general purpose rollup yet. The testnet for zkSync 2.0 [is public](https://blog.matter-labs.io/zksync-2-0-public-testnet-is-live-de870ba9632a), you may want to try it (though the server code is not open sourced just yet -- but will be, just later).
You may also want to read about [zkPorter](https://blog.matter-labs.io/zkporter-a-breakthrough-in-l2-scaling-ed5e48842fbf) -- another our take on the topic.

**Comment by LuozhuZhang** [comment]
> 

Yes, I tried EVM compatible with zksync v2 and the experience was very good.

I'm looking forward to reading the v2 source code and seeing the full zkEVM moduled.

I'm a little confused, can you tell me which commit of the master branch is stable, for me to read better.

**Comment by LuozhuZhang** [comment]
In addition, I want to make it clear that the current core team focus is zksync v2? So zksync will not have many updates?

As far as I know, the major feature of zkSync v2 is EVM compatibility (zkEVM), so is the current team's v2 focus on zkEVM?

> > Thanks for the reply, it sounds like the dev branch is more stable and better to read.
> 
> Actually, it just was not updated for a longer period of time. You can read and use it if you find it more convenient -- just keep in mind that it doesn't represent the current state of zkSync.
> 
> > Can you review my idea and tell me what's missing.
> 
> L3s are actually a hot topic right now, as well as limitless scalability in general. This sounds however that it would be more relevant for zkSync 2.0, since zkSync 1.0 is not general purpose rollup yet. The testnet for zkSync 2.0 [is public](https://blog.matter-labs.io/zksync-2-0-public-testnet-is-live-de870ba9632a), you may want to try it (though the server code is not open sourced just yet -- but will be, just later). You may also want to read about [zkPorter](https://blog.matter-labs.io/zkporter-a-breakthrough-in-l2-scaling-ed5e48842fbf) -- another our take on the topic.

**Comment by popzxc** [comment]
> I'm a little confused, can you tell me which commit of the master branch is stable, for me to read better.

The most recent commit (from 3 days ago) should work just fine.

> In addition, I want to make it clear that the current core team focus is zksync v2? So zksync will not have many updates?

Yes, we primarily work on v2. zkSync 1.0 receives stability & security updates, but from a feature set we consider it to be complete, meaning that we don't plan any big features on the protocol level. We still working with many projects on integrations though, like wallets, exchanges and offramp/onramp solutions.

>  so is the current team's v2 focus on zkEVM?

zkEVM is absolutely the central part of v2, but obviously it's not the only component -- we also need to prepare the new server that is web3 compatible, compiler and plugins for it, etc. But again, yes, everything revolves around zkEVM :)

**Comment by LuozhuZhang** [comment]
Thank you so much! You answered many of my doubts.

Looking forward to seeing the code for v2 and looking forward to doing some interesting things for this project.

> > I'm a little confused, can you tell me which commit of the master branch is stable, for me to read better.
> 
> The most recent commit (from 3 days ago) should work just fine.
> 
> > In addition, I want to make it clear that the current core team focus is zksync v2? So zksync will not have many updates?
> 
> Yes, we primarily work on v2. zkSync 1.0 receives stability & security updates, but from a feature set we consider it to be complete, meaning that we don't plan any big features on the protocol level. We still working with many projects on integrations though, like wallets, exchanges and offramp/onramp solutions.
> 
> > so is the current team's v2 focus on zkEVM?
> 
> zkEVM is absolutely the central part of v2, but obviously it's not the only component -- we also need to prepare the new server that is web3 compatible, compiler and plugins for it, etc. But again, yes, everything revolves around zkEVM :)
