### ISSUE TITLE
NoticePeriod may be mistaken

### ISSUE THREAD

**Issue by LBruyne** [matter-labs/zksync#384]
The getNoticePeriod method in zkSync.sol may have mistake. It returns 0 directly.
I believe it should return a config constant UPGRADE_NOTICE_PERIOD or the state variable approvedUpgradeNoticePeriod which may be shorter than UPGRADE_NOTICE_PERIOD with the cut of secure council.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/46318701/165903309-83f2bb39-493b-41e6-904e-d5083b2f6c2c.png">

**Comment by bxpana** [comment]
@LBruyne this is for zkSync 1.0 correct?

**Comment by LBruyne** [comment]
> @LBruyne this is for zkSync 1.0 correct?

I'm not sure yet. But the master branch contains this mistake now. I remember this master branch is for v2.0 now.

**Comment by bxpana** [comment]
Ok, let me see if I can get more information for you

**Comment by LBruyne** [comment]
This is my opinion:
``` Solidity
function startUpgrade(address[] calldata newTargets) external {
        requireMaster(msg.sender);
        require(upgradeStatus == UpgradeStatus.Idle, "spu11"); // spu11 - unable to activate active upgrade mode
        require(newTargets.length == managedContracts.length, "spu12"); // spu12 - number of new targets must be equal to the number of managed contracts

        uint256 noticePeriod = mainContract.getNoticePeriod();
        mainContract.upgradeNoticePeriodStarted();
        upgradeStatus = UpgradeStatus.NoticePeriod;
        noticePeriodFinishTimestamp = block.timestamp.add(noticePeriod);
        nextTargets = newTargets;
        emit NoticePeriodStart(versionId, newTargets, noticePeriod);
}

function startPreparation() external returns (bool) {
        requireMaster(msg.sender);
        require(upgradeStatus == UpgradeStatus.NoticePeriod, "ugp11"); // ugp11 - unable to activate preparation status in case of not active notice period status

        if (block.timestamp >= noticePeriodFinishTimestamp) {
            upgradeStatus = UpgradeStatus.Preparation;
            mainContract.upgradePreparationStarted();
            emit PreparationStart(versionId);
            return true;
        } else {
            return false;
        }
}
```

In this startUpgrade function in UpgradeGatekeeper.sol, noticePeriod is got from mainContract(ZkSync.sol) and used in startPreparation function to check whether to start the preparation work or not. However, this value is always 0 now. So the 'if'result in startPreparation function will always be true.

Also I notice that noticePeriod is configured by approvedNoticePeriod variable and can be shorten by a secure council. 
But the logic mentioned above still has some problem to fix.

**Comment by bxpana** [comment]
@LBruyne 
There are no errors in the upgrade logic, there is only legacy code that makes understanding the code difficult. `ZkSync.sol:getNoticePeriod` always return 0, and it is true that condition inside if statement on `UpgradeGatekeeper.sol:startPreparation` will be always true. However, `ZkSync.upgradePreparationStarted` will be called inside the execution of `the the UpgradeGatekeeper.sol:startPrepagation`. Here is actually checking the notice period.
```
 /// @notice Notification that upgrade preparation status is activated
    /// @dev Can be external because Proxy contract intercepts illegal calls of this function
    function upgradePreparationStarted() external override {
        require(block.timestamp >= upgradeStartTimestamp.add(approvedUpgradeNoticePeriod));

        upgradePreparationActive = true;
        upgradePreparationActivationTime = block.timestamp;
    }
```

**Comment by bxpana** [comment]
@LBruyne If the opinions are the same I'm not sure why we would modify the logic. We wouldn't need to modify the logic because there is nothing wrong with its current state.
