### ISSUE TITLE
Support perpetual contract

### ISSUE THREAD

**Issue by berryjam** [matter-labs/zksync#386]
How about support perpetual contract using zksync spot framework?

1. Add Trade、Liquidate、Oracle Price Transactions and releated circuit
2. Adapt the account balance tree to perpetual contract
3. Add Order Tree for proving the correctness of trade
4. Using Order book matching engine to match buyer and sellers' orders

**Comment by arose0** [comment]
This isn't planned for zkSync v1, because with v2 users will have a generalized L2 on which they can deploy functionality of their choosing.
