### ISSUE TITLE
Zksync v2 Goerli deposit ETH failed

### ISSUE THREAD

**Issue by lealife** [matter-labs/zksync#387]
I deposit some ETHs on https://portal.zksync.io/, but the balance on layer2 didn't change

Deposit transactions on layer1:
https://goerli.etherscan.io/address/0xb5579d69e99af08893f1eea561db25a261c7a999
![image](https://user-images.githubusercontent.com/1699428/171358540-4c3dda2c-1e63-4e0c-a2a5-0ed007a42c40.png)

Balance on https://portal.zksync.io/
![image](https://user-images.githubusercontent.com/1699428/171358618-17995c8a-5e2a-489f-b353-482c4c81b098.png)

**Comment by bxpana** [comment]
Did you end up getting your funds? Sounds like we might have had some downtime when you were trying to deposit. Can you try again and let us know if you still experience issues?
