### ISSUE TITLE
JavaScript SDK - React Native

### ISSUE THREAD

**Issue by lauhon** [matter-labs/zksync#392]
The Javascript SDK relies on WebAssembly for actions like `Wallet.fromEthSigner`

Since WASM is not available in react native(at least not per default) I'm wondering if and how it is possible to use the SDK (and zksync overall) in react native.

If there is a known way it would be awesome to have documentation about it. Or even if it is not possible at all it would be good to point that out in the docs. If it helps and you accept PR's from strangers I'm willing to do open a PR regaring it myself :)

**Comment by lauhon** [comment]
Possibly it is the best solution to handle zksync in native code via the zksync swift and java sdk's ?

**Comment by markin-io** [comment]
@lauhon I think zksync-rs could be built into native targets. 

Perhaps these links would help.
https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-21-rust-on-android.html
https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-06-rust-on-ios.html

**Comment by bxpana** [comment]
@lauhon maybe this will help you too? https://github.com/ExodusMovement/react-native-wasm

Now that we've moved a little further along with zkSync 2.0 have you had a chance to check out our JavaScript SDK? https://v2-docs.zksync.io/api/js/

**Comment by KimFol311** [comment]
I think to zksync-rs could be built into native targets.

**Comment by lauhon** [comment]
Thanks all for the answers!

**zksync-rs** -> would probably work, but requires a lot of knowledge and effort to get to work in react native.  
**v2 SDK** -> looking at [crypto.js](https://github.com/matter-labs/zksync/blob/1387e44b22f794910867132b361ac12222691268/sdk/zksync.js/src/crypto.ts) it looks like WebAssembly is now optional in order to use the SDK. Looks great!

I did not yet try it out myself, but I will close the Issue, assuming it is not a problem anymore
