### ISSUE TITLE
 run zksync prover  throw error

### ISSUE THREAD

**Issue by yanyanho** [matter-labs/zksync#395]
INFO zksync_prover::cli_utils: creating prover, worker name: yanyanho.local_1_blocks
thread 'main' panicked at 'failed to install Prometheus recorder: Hyper(hyper::Error(Listen, Os { code: 48, kind: AddrInUse, message: "Address already in use" }))', core/lib/prometheus_exporter/src/lib.rs:119:10
stack backtrace:

**Comment by bxpana** [comment]
Hello @yanyanho would you be able to provide more details on what's happening?

**Comment by yanyanho** [comment]
When I run "zk prover". it throws this error.  Follow the doc : https://github.com/matter-labs/zksync/blob/master/docs/launch.md

**Comment by bxpana** [comment]
@yanyanho did you already complete the setup? https://github.com/matter-labs/zksync/blob/master/docs/setup-dev.md

**Comment by yanyanho** [comment]
> @yanyanho did you already complete the setup? https://github.com/matter-labs/zksync/blob/master/docs/setup-dev.md

yes,thank you .
