### ISSUE TITLE
Can not get blknum after send the tx.

### ISSUE THREAD

**Issue by liuxiaobleach** [matter-labs/zksync#396]
It seems that when we try to get a tx receipt after send it. The block number in the receipt is always nil

example:
curl -X POST --data '{"jsonrpc":"2.0","id":6,"method":"eth_getTransactionReceipt","params":["0x5560b09aafecd147c60abcf070cd7f59bee92826ba0e426f1160c8d0c1cae9e8"]}'  https://zksync2-testnet.zksync.dev/ -H "Content-Type: application/json"

However, it will return blknum now. But it will not return blknum just after send the tx, while the it will return other receipt field.

**Comment by bxpana** [comment]
@liuxiaobleach this is report area is for zkSync 1.0. If you have issues to report for zkSync 2. you can use this repo https://github.com/matter-labs/zksync-v2-issues/blob/main/README.md
