### ISSUE TITLE
In the README.md, the link to the "zkSync SDK documentation" (https://zksync.io/api/sdk/) is broken. 

### ISSUE THREAD

**Issue by shafiquejamal** [matter-labs/zksync#398]
[zkSync SDK documentation](https://zksync.io/api/sdk/) leads to a "404 Not found" page.

**Comment by bxpana** [comment]
@shafiquejamal where in the documentation do you see that link?

**Comment by supernovahs** [comment]
https://github.com/matter-labs/zksync/pull/400

**Comment by shafiquejamal** [comment]
@bxpana I see you have corrected the link in https://github.com/matter-labs/zksync/pull/400. Thanks!

**Comment by bxpana** [comment]
Thanks @supernovahs and glad to know it's fixed. Thanks again for reporting @shafiquejamal
