### ISSUE TITLE
Javascript SDK - Vanilla JS

### ISSUE THREAD

**Issue by vlbhtcno1** [matter-labs/zksync#405]
For now JS SDK is only compatible with VueJS and ReactJS. Not compatible with Angular and VanillaJS

**Comment by bxpana** [comment]
@vlbhtcno1 are you talking about for zkSync 1.0 or zkSync 2.0?

**Comment by vlbhtcno1** [comment]
> @vlbhtcno1 are you talking about for zkSync 1.0 or zkSync 2.0?

zkSync 2.0

**Comment by bxpana** [comment]
Thanks for the suggestions, we'll look into these and see if support can be provided

**Comment by githubdoramon** [comment]
@vlbhtcno1 We are working hard on the evolution of our protocol - zkSync 2.0 - and the v2 SDK can be used in vanilla js projects (and I guess in Angular as well). If you really need the v1, feel free to submit some PRs that can make it compatible as well. Regards
