### ISSUE TITLE
How to Enroll Cronos EVM chain with ZKSync 2.0

### ISSUE THREAD

**Issue by cdc-Hitesh** [matter-labs/zksync#406]
Hey ZkSync team,
I am one of the blockchain engineers working with Crypto.com and currently exploring the L2 solutions for our EVM-compatible chain(Cronos) to achieve general-purpose computing using ZkSync.
It might not be a great channel to open the thread, yet I would appreciate any leads to take this forward.
Thanks

Please bear if wrongly tagged: @matterlabszoe @anton-matterlabs

**Comment by bxpana** [comment]
@cdc-Hitesh hello!! Thanks for reaching out. Right now the best way to contact us would be at hello@matter-labs.io and we can get you in touch with our business development team to see what would be possible.
