### ISSUE TITLE
The transaction is uploaded to the chain, but the error Transfer signature is incorrect is reported

### ISSUE THREAD

**Issue by hanzhenlong1314** [matter-labs/zksync#425]
https://zkscan.io/explorer/transactions/0xe5eb7c6cd177e4841357c15b6d1b708973c2c98ec1c90a9b881befc334aecdd8
![image](https://user-images.githubusercontent.com/25896081/225206324-3c3a5b1d-5f99-4914-a5d6-577ecdda7de5.png)

**Comment by hanzhenlong1314** [comment]
curl --location --request POST 'https://api.zksync.io/api/v0.2/transactions' \
--header 'Content-Type: application/json' \
--header 'Cookie: __cf_bm=3scnX0UQPjKAgKZOKdV.Mr4wWbibmMCUCTLZws.0QNU-1678853303-0-AabT/F975nvRohUS/3RVpnNHoxIJuv64ixY3UdBfIq/lj5/TRVJHK48VKmB/Y52rPFPhGSyKv54jS+nom6itoOs=' \
--data-raw '{
    "tx": {
        "type": "Transfer",
        "accountId": 1530192,
        "from": "0xd73c5e36d47eed32f0327f9d3f04b49384e90fab",
        "to": "0xd73c5e36d47eed32f0327f9d3f04b49384e90fab",
        "token": 0,
        "amount": 100000000000000,
        "fee": "50000000000000",
        "nonce": 1,
        "signature": {
            "pubKey": "a8955f3767915aae2a842c894cf58d36c2c76359c8dfbbf221004c2ada023d01",
            "signature": "c21a8b69e43111dee2d57d85654026be9cfdca845ed11641ca887e6a4d1e1922c879e6cfca9df727b3e98502471df27e101ba8694b755e8ca7a452f2e6d81303"
        },
        "validFrom": 0,
        "validUntil": 4294967295
    },
    "signature": {
        "type": "EthereumSignature",
        "signature": "0xd1dba295f7df2d6bb4cbb6fdd747a4297bc979ff04391ba853524911cc8566c2258795f0c7de2c40eda66d5e59fd5181024d1edaed46095e4de506b5532d4b4a1c"
    }
}'

**Comment by JeffXu1** [comment]
Why this issue is closed, how to fix it?
