### ISSUE TITLE
How to Develop and Deploy a Smart Contract on the Zks Lite Network?

### ISSUE THREAD

**Issue by wujunze** [matter-labs/zksync#426]
Hello,  I am an experienced programmer who has written Solidity smart contracts deployed on the ETH network. I am interested in deploying my own project on the zks lite network. Could you please advise me on what programming language to use? Also, can smart contracts written in Solidity be deployed on the zks lite network?

**Comment by Trional0** [comment]
You'd need to look into ZkSync Era for smart contracts deployment.
