### ISSUE TITLE
zkSync Era (v2.0 ) support?

### ISSUE THREAD

**Issue by dennisfurrer** [matter-labs/zksync#434]
Does this already support interaction with the "Era" network (I'm assuming that it doesn't); how can I best achieve what I'm trying to do? (i.e. programmatically bridge funds, send txs, trade, etc)

**Comment by bxpana** [comment]
> Does this already support interaction with the "Era" network (I'm assuming that it doesn't); how can I best achieve what I'm trying to do? (i.e. programmatically bridge funds, send txs, trade, etc)

There is not a native bridge between zkSync Lite and zkSync Era yet, but currently bridges like Orbiter Finance are providing solutions.
