### ISSUE TITLE
Deployed bytecode is not equal to generated one from given source.

### ISSUE THREAD

**Issue by hot3246624** [matter-labs/zksync#445]
When I went to verify the contract according to the official tutorial, I ran into this problem numerous times and I just couldn't figure out what was wrong. Here are the contracts from the test network, the contract address and construction parameters:
=========depoly info===========
Running deploy script for the Greeter contract
The deployment is estimated to cost 0.0398263345 ETH
constructor args:0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000094869207468657265210000000000000000000000000000000000000000000000
Greeter was deployed to 0xBF7a984347aF77Db3B02Ac269787be0d9f1A17d1

==========contract code=========
//SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.17;

contract Greeter {
    string private greeting;

    constructor(string memory _greeting) {
        greeting = _greeting;
    }

    function greet() public view returns (string memory) {
        return greeting;
    }

    function setGreeting(string memory _greeting) public {
        greeting = _greeting;
    }
}
==========end=============

**Comment by bxpana** [comment]
@hot3246624 feel free to join us on https://github.com/zkSync-Community-Hub/zkync-developers/discussions/categories/announcements for questions you can ask the community. 

Right now we are experiencing issues with verifying so this behavior is expected at the moment.
