### ISSUE TITLE
Access gild

### ISSUE THREAD

**Issue by Armankhan566** [matter-labs/zksync#452]
Why not eligible gild please acces my discord. Username. armani#0486.    
  Twitter. https://twitter.com/bihari_arman?t=L9vAwhooF2tRPwdPf-fyuw&s=09

Wallet : 0x88686F7A5Db76c4462efcc0b7CAE5c4F9A3c15F0

**Comment by avocadodefi** [comment]
you had to interact with any of the top NFT collections before the snapshot.

**Comment by rahman655** [comment]
which nft
