### ISSUE TITLE
Wallet Connect Error

### ISSUE THREAD

**Issue by bsk008** [matter-labs/zksync#474]
Wallet Connect not works properly,
Safeglobal not have any dapps!

**Comment by molodoy322** [comment]
Checked with myself, everything works bro, what exactly is your error?

**Comment by vanrangtho** [comment]
check network congestion Bro

**Comment by bsk008** [comment]
Wait i will add photo

**Comment by molodoy322** [comment]
> Wait i will add photo

okay, waiting

**Comment by bsk008** [comment]
Sorry dude i haven't checked for a while , now two dex are available on safe global and favourite jumper also there! :)

**Comment by molodoy322** [comment]
> Sorry dude i haven't checked for a while , now two dex are available on safe global and favourite jumper also there! :)

If there are any questions, feel free to ask in the last half year I've been fully into zkSync-development 😂
