### ISSUE TITLE
Add wnhedaxx to contributors

### ISSUE THREAD

**Issue by wnhedaxx** [matter-labs/zksync#479]
Hi zksync team! I’m claiming my contributor badge for completing the New Developer Toolkit tutorial.

Tutorial Repo: https://github.com/wnhedaxx/zksync

Requested badge: Tutorial

**Comment by cxllynx** [comment]
hmm

**Comment by KataKult** [comment]
nice

**Comment by 0xCalm** [comment]
not bad

**Comment by ReviBoi** [comment]
clear informations, but really so clear.
