### ISSUE TITLE
Zksync Library issues when trying to build it with electron application 

### ISSUE THREAD

**Issue by Taha-daboussi** [matter-labs/zksync#481]
Hi, I AM having issues when Trying to build my application when I have Zksync Library imported into my application 
when using it in the Dev Environment there will be no issue.

but when I build the application and try to open it I get this error 

![image](https://github.com/matter-labs/zksync/assets/68201777/40c51d15-480a-4f4e-a879-3f97ad3baa09)

Am not sure if this is related, But when I tried downloading it for the first time I got these error that I solved it by adding 
--force flag 

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: zksync-ethers@6.0.0
npm ERR! Found: ethers@5.7.0
npm ERR! node_modules/ethers
npm ERR!   ethers@"^5.1.0" from @arbitrum/sdk@3.1.12
npm ERR!   node_modules/@arbitrum/sdk
npm ERR!     @arbitrum/sdk@"^3.1.12" from the root project
npm ERR!   peer ethers@"^5.7.0" from zksync-web3@0.14.3
npm ERR!   node_modules/zksync-web3
npm ERR!     zksync-web3@"^0.14.3" from the root project
npm ERR!   2 more (the root project, zksync)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer ethers@"^6.7.1" from zksync-ethers@6.0.0
npm ERR! node_modules/zksync-ethers
npm ERR!   zksync-ethers@"^6.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: ethers@6.9.2
npm ERR! node_modules/ethers
npm ERR!   peer ethers@"^6.7.1" from zksync-ethers@6.0.0
npm ERR!   node_modules/zksync-ethers
npm ERR!     zksync-ethers@"^6.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!`

"zksync": "^0.13.1",
        "zksync-ethers": "^6.0.0",
        "zksync-web3": "^0.14.3"

**Comment by bxpana** [comment]
If you haven't already can you please open up a discussion on our Github Discussion page? The Github Discussion page is where the community can ask questions and get support from the team and the community https://github.com/zkSync-Community-Hub/zksync-developers/discussions
