### ISSUE TITLE
I can`t use zksync package for build at next.js, it will be a error.

### ISSUE THREAD

**Issue by Alan-Cn** [matter-labs/zksync#482]
Error: Cannot find module 'util'
next: 13.4.9
next webpack config: webpack: (config) => {
    config.resolve.fallback = {
      fs: false,
      net: false,
      tls: false,
      lokijs: false,
      encoding: false,
      'pino-pretty': false,
    }
    config.externals = [
      'pino-pretty',
      'lokijs',
      'encoding',
      ...(config.externals || []),
    ]
    return config
  },

I am sure there is a problem with this package because I have already ruled it out and finally confirmed it in zksync-crypto

**Comment by Alan-Cn** [comment]
"zksync": "^0.13.1"

**Comment by bxpana** [comment]
@Alan-Cn thanks for reaching out. Please create a post on our Github Discussion page https://github.com/zkSync-Community-Hub/zkync-developers/discussions to get support from the community
