### ISSUE TITLE
zksync-crypto in next.js cant build.

### ISSUE THREAD

**Issue by Alan-Cn** [matter-labs/zksync#483]
Can node and web versions in zksync-crypto be merged?
The current packaging method does not work in next.js because next.js requires server-side pre-rendering and client-side rendering.

can see my question: https://github.com/vercel/next.js/discussions/60868

**Comment by bxpana** [comment]
For support from our DevRel team and the community please create a discussion post on https://github.com/zkSync-Community-Hub/zkync-developers/discussions about this.
