### ISSUE TITLE
Incorrect language

### ISSUE THREAD

**Issue by 0xCalm** [matter-labs/zksync#493]
The language used in the summary of the description can be fine tuned.

Reword: Mani to Many

**Comment by Gappougne** [comment]
Thanks

**Comment by TRIBUNALS2** [comment]
> The language used in the summary of the description can be fine tuned.
> 
> Reword: Mani to Many

Yeah absolutely

**Comment by jcarlo-vs** [comment]
Cool, thanks.

**Comment by bxpana** [comment]
@0xCalm you can open a PR to make corrections for what you are seeing
