### ISSUE TITLE
Is zksync remix plugin safe?

### ISSUE THREAD

**Issue by HoseinNikmaramOfficial** [matter-labs/zksync#496]
hi
i found this plugin in remix https://github.com/NethermindEth/zksync-remix-plugin
i want to know is this plugin safe to deploy contract on zksync era ? or we have to deploy with introduced method in official docs ?

**Comment by amsator** [comment]
hi, here are some resources that you may find helpful:

    The zkSync Era Remix Plugin: A How-To Guide: [](https://medium.com/nethermind-eth/the-zksync-era-remix-plugin-a-how-to-guide-fc54e8d24bd3)

    How to deploy smart contract on zkSync Era Testnet using Remix and MetaMask: [](https://ethereum.stackexchange.com/questions/150695/how-to-deploy-smart-contract-on-zksync-era-testnet-using-remix-and-metamask)

I hope this helps!

**Comment by bxpana** [comment]
You can also check out our official docs for support with this too https://docs.zksync.io/build/tooling/ide.html#remix-ide
