### ISSUE TITLE
Integration Of Community Voting System on zKsync Website

### ISSUE THREAD

**Issue by MrExcel2019** [matter-labs/zksync#504]
**Background**

In order to have a swift community engagement and decision-making within zkSync ecosystem, I propose the integration of a community voting system directly into the website to   allow users to participate in the decision-making process, provide feedback, and contribute to the ecosystem.

**Observable Features**

1. Proposal Submission
2. Proposal Review and Approval Process
3. Transparent Voting Mechanism

 Furthermore, feedback and input from the community will facilitate the prioritization of initiatives that align with users' preferences, leading to product developments that are more pertinent and influential. In essence, the voting system will act as a medium for transparent discussions and cooperative efforts, reinforcing unity within the community and nurturing a feeling of membership and responsibility among its members.

**Comment by Mindstate1988** [comment]
I would like something like this implemented after TGE, so users can stake their tokens with validators and vote on proposals with their delegations.
