### ISSUE TITLE
The Feedback Form needs improvements

### ISSUE THREAD

**Issue by streamust** [matter-labs/zksync#505]
The [zkSync Experience Feedback Survey form](https://docs.google.com/forms/d/e/1FAIpQLSfWD7bUGxmKNdxzeWrijC0xqVS8Hlz9KSrRqg4BqDIw6C0XKg/viewform?fbzx=-327973254725244992) has incorrect instructions.

Discord instructions state the following: 
_If you have any feedback as a Developer **`or`** User, fill out the form._

However, the form cannot be submitted unless both User questions **`and`** Developer questions are filled out. 

This can be fixed by making all questions non-mandatory, or by creating separate forms for Users and Developers.

**Comment by bxpana** [comment]
Thanks got that fixed now.
