### ISSUE TITLE
Is this written properly ? 

### ISSUE THREAD

**Issue by shreez8** [matter-labs/zksync#507]
https://github.com/matter-labs/zksync/blob/0a4ca2145a0c95b5bafa84c2f095c644907a8825/sdk/zksync.js/src/typechain/Governance.d.ts#L709

In line number 709 while calling token..( ) . is adding unit16 like that is neccessary?

**Comment by ladzin2000** [comment]
the line `"tokenAddresses(uint16)"` specifies a function signature for the `tokenAddresses` function that accepts a parameter of type `uint16`. This indicates that the function expects an argument of type `uint16` when it is called.

So, yes, the inclusion of `uint16` in the function signature is necessary to indicate the data type of the argument expected by the function `tokenAddresses`. This helps ensure type safety and proper handling of the input parameters when interacting with the function.
