### ISSUE TITLE
zksync-hello world

### ISSUE THREAD

**Issue by rovicsum** [matter-labs/zksync#512]
https://github.com/rovicsum/zksync-hello-world

Hello zksync I want to learn more about zksync is there any more resources that I could refer into. And did I made the right thing in pushing into github and creating the smart contract and interacting with it.

Hoping to learn more.

**Comment by FabioT81** [comment]
what do you want to know specifically?

**Comment by rovicsum** [comment]
Hello thank you for asking!

Are you part of the team?

I want to know more about the fundamentals of zk-proofs, how to create a more complex smart contract, etc. I am planning to also share my knowledge to a small community. 

If you could point me to the right resources that would be great! Thank you so much!
