### ISSUE TITLE
Allow Interoperable to wormhole

### ISSUE THREAD

**Issue by eleonoregraf10** [matter-labs/zksync#514]
https://wormhole.com/
https://github.com/wormhole-foundation/wormhole

Interoperability Protocols Play A Crucial Role In Enabling Communication & Interaction Between Different Systems, Software Applications & Technologies.

At The Moment zksync Is Deployed On Orbiter, Owlto, Rhino, Layerswap & Layerzero But Its Not Deployed On Other Interoperability Protocols That Connects It To Other Evm, Non Evm & L1 Blockchains Like Solana Near Fuse Aptos Sei Oasis & A Lot More

Deploying zksync on, Wormhole, Would Connect A Long List Of L1 & Non Evm Blockchains Tozksync, There By Enabling Easy Acccessibilty & A Very Fast Onboarding.

**Comment by Matttioboy** [comment]
excellent idea
