### ISSUE TITLE
Integrate zkSync to Aptos Bridge

### ISSUE THREAD

**Issue by Matttioboy** [matter-labs/zksync#515]
Transferring Assets from Aptos to Other Chains

Transferring assets from Aptos back to other chains (ex. Ethereum) does not require additional registration or claim transactions. Transfers out of Aptos are subject to a 2 to 3 day waiting period before the transaction is completed. This waiting period is for security purposes and allows for a significant number of blocks to be finalized before relaying messages to non-Aptos chains.

<img width="586" alt="image" src="https://github.com/matter-labs/zksync/assets/155030398/12bd9315-5739-4b90-9abe-8a995fbcadd4">

**Comment by Deno1989** [comment]
fully support this bridge
