### ISSUE TITLE
COLLABORATE WITH LOGX PERP DEX

### ISSUE THREAD

**Issue by 3nety** [matter-labs/zksync#517]
LogX is a perp that launched q3 mainnet 2023, they got so many things going for them since then plus a great community behind them. I know with the integration of Zksyn on that perp dex, it will boost Zksync TVL, and also get more buzz and excitement to Zksync just as gmx/arb. Also launch some integration quest on LogX alerting people about the integration too.

**Comment by Whizzy6868** [comment]
Nice project zkysnc needs to come in

**Comment by beauty242** [comment]
I would love to trade future on zksync ✅

**Comment by abdlkdrsncr** [comment]
linea ağında kullanmıştım, zksyncta da iyi olabilir tabi
