### ISSUE TITLE
Reduce fees of native bridge and add options to bridge for other L2's

### ISSUE THREAD

**Issue by Mindstate1988** [matter-labs/zksync#521]
One of the most important characteristics of ZKSync is the hyperscalability and with that the reduction of transaction fees. This works very well with txn costs all throughout the ecosystem. 

However, the native bridge does not. The bridge fee is relatively high and reduces the onboarding possibilities of new users.

I propose that ZKSync adds possibilities to bridge from chains like ARB and OP to ZKSync mainnet to increase the onboarding of new users. We know this is possible at reduced costs since third-party operators are able to do so as well.

Thanks for your consideration.

**Comment by abdlkdrsncr** [comment]
bu öneri sybil riskini arttırabilir
