### ISSUE TITLE
Paymaster Link broken 

### ISSUE THREAD

**Issue by Yanimartiny** [matter-labs/zksync#523]
https://docs.zksync.io/build/sdks/go/examples/custom-paymaster/use-paymaster.html

<img width="1163" alt="zksync" src="https://github.com/matter-labs/zksync/assets/149122079/da46f41f-6316-4b74-a377-47dab3b1ceb7">

**Comment by ultratwo** [comment]
All of those issues are "github farming" spam following those tweets (+200k impressions) : https://twitter.com/Abrahamchase09/status/1759101213381959960

**Comment by efty21** [comment]
Good

**Comment by Seuncoded** [comment]
It's has been fixed
