### ISSUE TITLE
OTC on Zksync

### ISSUE THREAD

**Issue by FabioT81** [matter-labs/zksync#526]
Hello everyone, in a rapidly evolving market there is a sector that will certainly bring great value to the world of cryptocurrencies: the OTC market. There is no protocol on Zksync that offers this service. This is the right time to enrich our ecosystem with a new product. What do you think? Is this an idea that convinces you? Write your opinion, positive or negative.

**Comment by amsator** [comment]
I think there are good solutions on other blockchains with cheaper transactions... and so it would be nice for the ecosystem
