### ISSUE TITLE
Gas fees for staking on zkSync

### ISSUE THREAD

**Issue by Blisshh** [matter-labs/zksync#531]
I have encountered various issues when staking as gas fees are strangely high when attempting to deposit or withdraw.

One instance is with reactor fusion, link : https://main.reactorfusion.xyz/stake

I believe the cost was over $6 usd (may have been extraordinary high gwei price) however this is consistent thought other protocols I have / continue to use..

I am just wondering is this a poor timing issue from myself, or this remains consistent with these contracts. 

Cheers

**Comment by amsator** [comment]
it seems that this is due to the price of gas, it seems that the ethereum update should be released soon

**Comment by Seuncoded** [comment]
It's back to normal and everything works perfectly now

**Comment by Blisshh** [comment]
Its funny, since the post the coin has gone up 2 / 3x so that's covered the gas fees nicely

**Comment by jayaabadi88** [comment]
> Its funny, since the post the coin has gone up 2 / 3x so that's covered the gas fees nicely

understood

**Comment by jayaabadi88** [comment]
> It's back to normal and everything works perfectly now

yes fantastic

**Comment by jayaabadi88** [comment]
![Uploading karaoke .png…]()

**Comment by Blisshh** [comment]
> > Its funny, since the post the coin has gone up 2 / 3x so that's covered the gas fees nicely
> 
> understood

high 5
