### ISSUE TITLE
Gas fees on Metamask Unusually High

### ISSUE THREAD

**Issue by InnoOkeke** [matter-labs/zksync#535]
I've been trying to mint NFT on hypercomic and also perform some swaps.

The gas fees are usually high as compared to the very low fees I was paying few days ago. 

What's the best way to resolve this? Or should I try performing the transactions when gas price is low???

**Comment by Vispilio** [comment]
you need to manually lower the gas fee, and if the network is congested and your transaction fails, just try at a more quiet moment, it will eventually go through with the modest fees you'll be setting...

**Comment by toanutt** [comment]
Depending on the time, the gas fee for transactions is different, so be patient in choosing a time of day when the gas level is low.

**Comment by InnoOkeke** [comment]
> Depending on the time, the gas fee for transactions is different, so be patient in choosing a time of day when the gas level is low.

That's what i'll do. Thanks

**Comment by InnoOkeke** [comment]
> you need to manually lower the gas fee, and if the network is congested and your transaction fails, just try at a more quiet moment, it will eventually go through with the modest fees you'll be setting...

Thanks
