### ISSUE TITLE
Integration to Zora

### ISSUE THREAD

**Issue by Whizzy6868** [matter-labs/zksync#536]
Zora is an Ethereum Virtual Machine (EVM)-compatible Layer 2 blockchain platform designed to efficiently support tokenized digital media and non-fungible tokens (NFTs). A key goal of the Zora Network is to provide NFT creators and buyers with improved scalability, faster transaction speeds, and lower costs. Zksync should also be part of a network that is used to pay on Zora. Zksync should also be integrated into bridge into Zora on Zora network.

**Comment by ladzin2000** [comment]
It sounds like you're proposing integrating zkSync into the Zora Network to enhance scalability, transaction speed, and reduce costs for NFT creators and buyers. Integrating zkSync, a Layer 2 scaling solution, into the Zora Network could indeed help achieve those goals by offloading transactions from the Ethereum mainnet to a more efficient and cost-effective layer.

By integrating zkSync into the Zora Network, users could benefit from faster transaction speeds and lower fees while still retaining the security guarantees of the Ethereum mainnet. Additionally, integrating a bridge into zkSync would allow users to seamlessly transfer assets between zkSync and the Ethereum mainnet, enhancing interoperability and accessibility for users.

**Comment by Whizzy6868** [comment]
The first paragraph is correct then then second paragraph I mean transfer of asset between Zksync and Zora mainnet. Then Zksync should be used to mint NFT on Zora

Please let me know if you need further explanation or screenshot

**Comment by beauty242** [comment]
if i can use zksync to mint on zora it will save me more fees. nice one
