### ISSUE TITLE
integrate wstETH-pool-bridge- stargate

### ISSUE THREAD

**Issue by ed01512** [matter-labs/zksync#538]
The ability to transfer wstETH from zksync to Stargate would allow users to seamlessly transfer wstETH with Scroll (avoiding the mainnet due to excessively high fees), increasing interoperability, flexibility in managing their digital assets, and scalability.

LP wstETH on stargate:
.Access to new investment opportunities
.Users can diversify their portfolio

**Comment by jayaabadi88** [comment]
yes agree
