### ISSUE TITLE
Integrate Zksync with Opensea

### ISSUE THREAD

**Issue by otnaesoj009** [matter-labs/zksync#551]
While zksync is integrated with nftmarketplaces like element, zonic etc i found out that it is not integrated with the largest nft marketplace OPENSEA hence affecting the overall nft market in Zksync ecosystem.

**Comment by ProfParadox123** [comment]
Completely agree , Zksync should be integrated with opensea  for more adaptability and decentralization

**Comment by zerosolid** [comment]
Interesting point, but perhaps it would make sense to be more forward looking and consider an up and coming marketplace like Magic Eden. They are the number 1 ordinals marketplace, number 2 for solana (previously number 1) and launching Eth this week.
