### ISSUE TITLE
Integration ZkSync Lite w/ Jumper

### ISSUE THREAD

**Issue by holdmaster90** [matter-labs/zksync#556]
Orbiter is quite buggy at times and having another option is always fantastic. 

Have we considered looking at integration ZkSync Lite w/ jumper?

**Comment by jarvisssan** [comment]
indeed same probleme

**Comment by searchhh123** [comment]
Integrating more projects for ZKSync Lite is a great idea, I agree!

**Comment by 954460959** [comment]
Need team support
