### ISSUE TITLE
Enhance Native Bridge Functionality and Reduce Fees for Improved User Onboarding

### ISSUE THREAD

**Issue by AfricanAlp** [matter-labs/zksync#576]
While zkSync's native bridge offers a seamless way to transfer assets, its current fee structure may hinder new user onboarding. To address this, I propose enhancing the native bridge to reduce fees and adding support for bridging to zkSync mainnet. This expansion will not only improve user accessibility but also align with zkSync's mission of providing a cost-effective and scalable solution for decentralized transactions.

Goals to be achieved.
1. Reduction in fees: Decrease the fees associated with using the native bridge to make it more accessible to new users.
2. Usability: Enhance the overall user experience by providing more options and reducing barriers to entry for zkSync.

Expected Benefits.
1. Improved Accessibility: Lower fees and multi-L2 bridge support will attract more users to zkSync, enhancing its adoption and ecosystem growth.
2. Competitive Edge: By offering a more cost-effective and versatile bridging solution, zkSync can differentiate itself from competitors and establish a stronger position in the market.

Proposed solutions.
1. Fee Optimization.
2. Multi-L2 Bridge Integration.
4. Testing and Deployment.

**Comment by nathanlwb** [comment]
I agree enhancing the native bridge and reducing fees is crucial for user onboarding. While the Dencun upgrade provides gas fee reductions, optimizing bridge fees specifically will make zkSync even more attractive to newcomers.  Multi-L2 bridge support further streamlines the process. This aligns perfectly with zkSync's goal of accessibility and scalability.
