### ISSUE TITLE
Zksync Era & LIte 1st Airdrop Criteria

### ISSUE THREAD

**Issue by Maruful1122** [matter-labs/zksync#590]
I suggest zksync criteria to be something like this:

As per https://dune.com/KARTOD/zksync-evms-mega-dashboard analysis zksync era has over 5.9 million user. There should be a minimum requirement to be eligible for airdrop. 
in my opinion minimum criteria should be:
Zksync- Era

1. Used zksync for at least 3 separate months.
2. minimum 25 transaction on zksync blockchain.
3. transacted at least 150$ total volume or 15+ NFT transaction.
4. minimum 7 active days.
5. minimum 5 unique contract.

After one is eligible for airdrop, they get rewarded with token instead of points when they satisfy specific criteria. these criteria includes:

1. used zksync for 3 separate month -> 50 zks
2. used zksync for 6 separate month -> 100 zks
3. used zksync for 10 separate month -> 200 zks
4. 7 active days -> 10 zks 
5. 15 active days -> 25 zks
6. 25 active days -> 50 zks
7. 50 active days -> 150 zks
8. native bridge user -> 50 zks
9. bridge volume 2000$ -> 50 zks
10. bridge volume 15000$ -> 100 zks
11. bridge volume 75000$ -> 150 zks
12. bridge volume 150000$ -> 250 zks
13. trading volume 150$ -> 25 zks
14. trading volume 2000$ -> 50 zks
15. trading volume 20000$ -> 100 zks
16. trading volume 75000$ -> 150 zks
17. trading volume 150000$ -> 200zks
18. 25 transaction -> 10 zks
19. 50 transaction -> 25 zks
20. 100 transaction -> 50 zks
21. 200 transaction -> 100 zks
22. 5 unique contract -> 25 zks
23. 15 unique contract -> 50 zks
24. 30 unique contract -> 100 zks
25. 5+ nft transaction -> 10 zks
26. 15+ nft transaction -> 25 zks
27. 30+ nft transaction -> 50 zks
28. used pay master feature 3 times -> 15 zks
29. donated in gitcoin -> 25 zks
30. LIBERTAS OMNIBUS NFT holder -> 200zks
31. provide liquidity 15$ (minimum 7 days hold)  -> 10 zks
32. provide liquidity 150$ (minimum 7 days hold)  -> 50 zks
33. provide liquidity 1500$ (minimum 7 days hold)  -> 150 zks
34. provide liquidity 15000$ (minimum 7 days hold)  -> 300 zks
35. 

multipliers: (not stackable , user only get highest one)
1. 15+ gitcoin score or 10 transaction on eth mainnet -> 1.1x
2. 20+ gitcoin score or bab token holder or 30+ eth transaction -> 1.3x
3. 50+ eth transaction -> 1.4

zk-lite:
minimum requirements to be eligible for zk-lite airdrop
1. minimum 25 transaction
2. trading volume 150$ 
3. 4 separate active month 

criteria:
1. 25 transaction -> 10 zks
2. 50 transaction -> 25 zks
3. 100 transaction -> 50 zks
4. trading volume 150$ -> 10 zks
5. trading volume 1500$ -> 25 zks
6. trading volume 15000$ -> 50 zks
7. 4 separate active month -> 10 zks
8. 8 separate active month -> 25 zks
9. 12 separate active month -> 50 zks
10. 16 separate active month -> 100 zks 
11. bridge volume 150$ -> 25 zks
12. bridge volume 1500$ -> 50 zks
13. bridge volume 15000$ -> 100 zks

we will take a new step against sybil wallets . we will divide the eligible wallets in 3 category. 1. A genuine wallet 2. could be a sybill wallet 3. high chance of being a sybil wallet.

1. A genuine wallet will get 100% of their earned token.
2. A wallet that has a possibility of being a sybil wallet will get 50% of their earned token.
3. A wallet that has a very high possibility of being a sybil wallet will get 10% of their earned token.
NOTE: An identified sybil wallet will get nothing.

*** According to my research, zksync has over 5.8 million users. With the criteria I preferred , around 40% of them will be eligible for the airdrop. assuming total supply of ZKS will be 10 billion, almost 1.5 billion to 2billion ZKS token will be used for first phrase of airdrop. If there are too much eligible user , then I prefer the rewards to be reduced by a small margin to keep the balance between token and user.

**Comment by Hazemabuzer** [comment]
Fair enough

**Comment by enerelt0418** [comment]
Fair enough

**Comment by enerelt0418** [comment]
i would prefer omnibus nft, gitcoin points, arbitrum criteria, starknet criteria, zk-flow information.  this criteria full enough for community.

**Comment by FabioT81** [comment]
> Preferirei omnibus nft, punti gitcoin, criteri arbitrum, criteri starknet, informazioni sul flusso zk. questo criterio è sufficientemente completo per la comunità.

Many Starknet users have always used the chain since day 1 but have not obtained even a token. The discontent among the community is very great.

The last major truly inclusive airdrop was Arbitrum, and in fact the Arbitrum community is one of the strongest. Users don't forget. Wallet age, swap/liquidity/bridge volume, consistency in using the chain. These are the really important parameters.

**Comment by elisee26** [comment]
A couple of additions I can think of off the top of my head:
(1) points for holders of other NFT communities to encourage their onboarding, e.g, Pudgy penguins
(2) at least 5-10 transactions using a multisig wallet like Gnosis safe

**Comment by HYeonJoc** [comment]
zksync is the mainnet, 
There are items that are not related to the mainnet.

1. Donate gitcoin

2. gitcoin score

3. Ownership of Bobcoin

It's the zksync era, but the light condition is too tricky, 
I think it's right to see Wright as a minimum condition

And lastly, I think it's right to raise the payment master's trading volume a little more

**Comment by HYeonJoc** [comment]
And finally, the zksync team will do well on their own, 
Don't try to teach them, your look like beggars
The criteria will be set by them.
If you do your best, the results will be good

**Comment by elisee26** [comment]
> zksync is the mainnet, There are items that are not related to the mainnet.
> 
> 1. Donate gitcoin
> 2. gitcoin score
> 3. Ownership of Bobcoin
> 
> It's the zksync era, but the light condition is too tricky, I think it's right to see Wright as a minimum condition
> 
> And lastly, I think it's right to raise the payment master's trading volume a little more

1. Gitcoin donation can be important if you're donating to projects building on zksync, you're in a way helping the growth of the ecosystem. Optimism used that as a multiplier
2. Gitcoin score: it's not the best way but there's got to be a way to filter out those sybil factory farmers, or at least apply some penalty in the form of allocation reduction
3. Agree that Binance BAB token shouldn't be a factor at all. Binance doesn't operate in many countries.

**Comment by HYeonJoc** [comment]
I admit to a certain extent, But Optimism is too old-fashioned 
It seems rather more reasonable to set the bar as arb, but this is only my subject

**Comment by HYeonJoc** [comment]
> > zksync is the mainnet, There are items that are not related to the mainnet.
> > 
> > 1. Donate gitcoin
> > 2. gitcoin score
> > 3. Ownership of Bobcoin
> > 
> > It's the zksync era, but the light condition is too tricky, I think it's right to see Wright as a minimum condition
> > And lastly, I think it's right to raise the payment master's trading volume a little more
> 
> 1. Gitcoin donation can be important if you're donating to projects building on zksync, you're in a way helping the growth of the ecosystem. Optimism used that as a multiplier
> 2. Gitcoin score: it's not the best way but there's got to be a way to filter out those sybil factory farmers, or at least apply some penalty in the form of allocation reduction
> 3. Agree that Binance BAB token shouldn't be a factor at all. Binance doesn't operate in many countries.

I admit to a certain extent, But Optimism is too old-fashioned
It seems rather more reasonable to set the bar as arb, but this is only my subject

**Comment by HYeonJoc** [comment]
> And finally, the zksync team will do well on their own, Don't try to teach them, your look like beggars The criteria will be set by them. If you do your best, the results will be good

There are many ways to catch a Civil.
1. Whether Ethereum Mainnet is used or not
2. zksync Mainnet activation period (minimum 90 days)
3. Last zks coin count verification request ip redundancy
4. Farming wallet moving from farming wallet to farming wallet
5. Minimum tx 50 tx 
6. Gas consumption (minimum 100$)

Wouldn't it be enough to judge that it's a sybil wallet if any of these are included?

**Comment by NDT3117** [comment]
Great to see this

**Comment by sunarus** [comment]
Sounds good
