### ISSUE TITLE
Very high gas disincentivizes liquidity providers

### ISSUE THREAD

**Issue by FabioT81** [matter-labs/zksync#595]
After trying to sell an nft on Ethereum worth $40 (gas $148), I tried to provide liquidity on Syncswap (Era) but again I had to give up because I would have had to pay $4.74. For a Layer2 this is an insane figure. A few days ago I gave up trading on Holdstation because the gas to pay for a simple swap was very high, $4.8. No, that's not good. This is a huge limitation for our L2. 90% of users cannot afford to pay those amounts. Network congestion cannot be a valid justification.

![sync](https://github.com/matter-labs/zksync/assets/117509586/9b2f16b3-cd7c-4495-85b8-f5be9ef683ce)

**Comment by nathanlwb** [comment]
I understand your frustration with the high fees on Layer 2 like zkSync especially during busy traffic. However, after the recent DenCun upgrade, the gas fee has been significantly reduced.
