### ISSUE TITLE
Prover Build Fails During CUDA Object Compilation (__shared__ Variable Initialization Error)

### ISSUE THREAD

**Issue by Szczepoo13** [matter-labs/zksync#632]
Dear MatterLabs team,
I am encountering an issue when running the prover. Specifically, when I execute the command '**zk_inception prover run**'
the build of **boojum-cuda v0.150.4** does not complete, PTX JIT spills registers and I encounter the following error: initializer not allowed for __shared__ variable
![error1part](https://github.com/user-attachments/assets/eb3d15bf-5980-4b91-b174-257445fac109)
![error2part](https://github.com/user-attachments/assets/13280387-83d7-418b-accb-b51fe29280e6)

I am unsure if this is related to a misconfiguration in my CUDA setup or something else. Could you please advise on potential solutions or debugging steps I can take? 
My environment details:
GCC: 12.3.0
CMake: 3.30.2
NVCC: 11.5, V11.5.119
Clang: 14.0.0
Rustup - nightly-x86_64-unknown-linux-gnu

Output from nvidia-smi, in case it helps:
![nvidia-smi](https://github.com/user-attachments/assets/2837d219-d949-430f-8511-80c2128fb6eb)

I have also tested my env with NVIDIA CUDA samples, and all tests pass successfully (see figure below):
![cuda-test](https://github.com/user-attachments/assets/4823f69b-42e1-4207-af92-fe3bd2fcf7b7)

Additional screenshot of when command for running prover stops running:
![error3part](https://github.com/user-attachments/assets/f7646f12-6efa-4af7-806c-fd6a003bc539)

Thank you for your help, this issue has been bothering me for quite some time

**Comment by bxpana** [comment]
If you're having issues you can open up a discussion at https://github.com/zkSync-Community-Hub/zkync-developers/discussions and we can help you there.
